// ==UserScript==
// @name         Wavez Tools (all-in-one)
// @namespace    https://wavez.fm/
// @author       fluteds
// @icon         https://wavez.fm/favicon.ico
// @version      2026.08.28
// @updateURL    https://github.com/fluteds/wavez/raw/main/userscripts/wavez-all.user.js
// @downloadURL  https://github.com/fluteds/wavez/raw/main/userscripts/wavez-all.user.js
// @description  Every Wavez userscript in one install. Toggle features from the userscript manager menu.
// @match        https://wavez.fm/*
// @match        https://*.wavez.fm/*
// @grant        GM_registerMenuCommand
// @grant        GM_xmlhttpRequest
// @grant        unsafeWindow
// @connect      clients5.google.com
// @connect      niceatc.api.br
// @connect      woot.niceatc.api.br
// @run-at       document-start
// ==/UserScript==

// GENERATED by sync-scripts.sh. Edit the individual scripts, not this file.

(function () {
  'use strict';

  // Taking a @grant sandboxes us, and the page-context scripts below reach for
  // page globals (window.WavezFM). Hand them the real window so they still work.
  var PAGE = typeof unsafeWindow !== "undefined" ? unsafeWindow : window;

  var KEY = "wavez-tools:";
  function on(id, dflt) { return (localStorage.getItem(KEY + id) || dflt) === "on"; }

  // The manager already has a menu. Native beats a settings panel we maintain.
  function menu(id, label, dflt) {
    var isOn = on(id, dflt);
    if (typeof GM_registerMenuCommand !== "function") return isOn;
    GM_registerMenuCommand((isOn ? "✓ " : "✕ ") + label, function () {
      localStorage.setItem(KEY + id, isOn ? "off" : "on");
      location.reload();
    });
    return isOn;
  }

  if (menu('translate', 'Wavez Translate', 'on')) (function (window) {

    // CONFIG Language to translate INTO (ISO code: "en", "es", "pt", "ja", ...).
    var TARGET_LANG = "en";

    // How translations show (WZTranslate.setMode live): "append" adds a line beneath, "replace" swaps in place, "hover" crossfades on hover.
    var DISPLAY_MODE = "append";

    // Only translate messages NOT already in TARGET_LANG (uses Google's detected source language). Set false to translate everything.
    var ONLY_NON_TARGET = true;

    // Max simultaneous translation requests (keeps the free endpoint from rate-limiting).
    var MAX_INFLIGHT = 4;

    // --------------------------------------------------------------------------
    (function () {
      "use strict";

      // Chat bodies carry a wavez token (stable across themes). System callouts don't, so we anchor off the callout icon's class and grab the paragraph beside it.
      var MSG_SELECTOR =
        '[class*="wavezfm-chat-text-size"], .wavezfm-centered-icon + div > p';

      var config = {
        target: TARGET_LANG,
        mode: DISPLAY_MODE,
        onlyNonTarget: ONLY_NON_TARGET,
        enabled: true,
      };

      // --- styling -------------------------------------------------------------
      var style = document.createElement("style");
      style.textContent =
        ".wz-translation{display:block;margin-top:2px;opacity:.6;font-style:italic;" +
        "font-size:var(--wavezfm-chat-text-size,13px);line-height:var(--wavezfm-chat-line-height,1.25rem)}" +
        ".wz-translation::before{content:'\\1F310\\00A0';opacity:.7}" +
        ".wz-replaced::before{content:'\\1F310\\00A0';opacity:.5;font-size:.85em}" +
        ".wz-hover{cursor:pointer;transition:opacity .15s ease,transform .15s ease}" +
        ".wz-hover.wz-swap{opacity:0;transform:translateY(3px)}";
      (document.head || document.documentElement).appendChild(style);

      // --- cross-origin GET (GM first, fetch fallback) -------------------------
      function httpGet(url) {
        return new Promise(function (resolve, reject) {
          if (typeof GM_xmlhttpRequest === "function") {
            GM_xmlhttpRequest({
              method: "GET",
              url: url,
              onload: function (r) {
                resolve(r.responseText);
              },
              onerror: reject,
              ontimeout: reject,
            });
            return;
          }
          if (typeof GM !== "undefined" && GM.xmlHttpRequest) {
            GM.xmlHttpRequest({
              method: "GET",
              url: url,
              onload: function (r) {
                resolve(r.responseText);
              },
              onerror: reject,
              ontimeout: reject,
            });
            return;
          }
          // No GM API (e.g. raw injection): the endpoint sends CORS *, so plain fetch works in most setups.
          fetch(url)
            .then(function (r) {
              return r.text();
            })
            .then(resolve, reject);
        });
      }

      // --- concurrency-limited queue -------------------------------------------
      var inflight = 0;
      var queue = [];
      function pump() {
        while (inflight < MAX_INFLIGHT && queue.length) {
          var job = queue.shift();
          inflight++;
          job().then(release, release);
        }
      }
      function release() {
        inflight--;
        pump();
      }
      function enqueue(fn) {
        return new Promise(function (resolve, reject) {
          queue.push(function () {
            return fn().then(resolve, reject);
          });
          pump();
        });
      }

      // translation cache: original text -> { text, src }
      var cache = Object.create(null);

      function translate(text) {
        if (cache[text]) return Promise.resolve(cache[text]);
        return enqueue(function () {
          // dict-chrome-ex (Google Dictionary extension's endpoint) is far less rate-limited than client=gtx, which bot-blocks a burst of messages on room load. Shape: [["translated text","src lang"]].
          var url =
            "https://clients5.google.com/translate_a/t?client=dict-chrome-ex&sl=auto&tl=" +
            encodeURIComponent(config.target) +
            "&q=" +
            encodeURIComponent(text);
          return httpGet(url).then(function (raw) {
            var data = JSON.parse(raw);
            var seg = data[0] || [];
            var result = { text: seg[0] || "", src: seg[1] || "" };
            cache[text] = result;
            return result;
          });
        });
      }

      // --- rendering -----------------------------------------------------------
      function clearTranslation(el) {
        if (el._wzNode && el._wzNode.parentNode) {
          el._wzNode.parentNode.removeChild(el._wzNode);
        }
        el._wzNode = null;
        if (el._wzOriginal != null) {
          el.textContent = el._wzOriginal;
          el._wzOriginal = null;
        }
        if (el._wzHover) {
          // Restore the original markup if we're mid-swap, then drop hover state.
          if (el._wzHover.shown) el.innerHTML = el._wzHover.html;
          el._wzHover = null;
        }
        el.classList.remove("wz-hover", "wz-swap", "wz-replaced");
        el.removeAttribute("title");
      }

      // Crossfade original/translation on hover; a busy flag keeps the observer from reacting to our own swaps.
      function swapHover(el, toTranslated) {
        var h = el._wzHover;
        if (!h || h.shown === toTranslated) return;
        h.shown = toTranslated;
        el._wzBusy = true;
        el.classList.add("wz-swap"); // fade + nudge out
        window.setTimeout(function () {
          if (!el._wzHover) {
            el.classList.remove("wz-swap");
            el._wzBusy = false;
            return;
          }
          if (toTranslated) el.textContent = h.translated;
          else el.innerHTML = h.html;
          el.classList.remove("wz-swap"); // fade back in
          // Clear busy after the mutation records have been delivered.
          window.setTimeout(function () {
            el._wzBusy = false;
          }, 0);
        }, 150);
      }

      function setupHover(el, translated) {
        el._wzHover = { html: el.innerHTML, translated: translated, shown: false };
        el.classList.add("wz-hover");
        if (!el._wzHoverBound) {
          el._wzHoverBound = true;
          el.addEventListener("mouseenter", function () {
            swapHover(el, true);
          });
          el.addEventListener("mouseleave", function () {
            swapHover(el, false);
          });
        }
      }

      function render(el, original, translated) {
        clearTranslation(el);
        if (config.mode === "replace") {
          el._wzOriginal = original;
          el.textContent = translated; // drops inline emoji <img>; use hover mode to keep them
          el.classList.add("wz-replaced"); // leading 🌐 marks the swap
          el.title = original;
          return;
        }
        if (config.mode === "hover") {
          setupHover(el, translated);
          return;
        }
        // append (default)
        var node = document.createElement("span");
        node.className = "wz-translation";
        node.textContent = translated;
        el._wzNode = node;
        el.parentNode.insertBefore(node, el.nextSibling);
      }

      // At least two letters worth translating (skip pure emoji/numbers/links).
      var LETTERS = /\p{L}{2,}/u;

      function process(el) {
        if (!config.enabled || el._wzBusy) return;
        var original = (el.textContent || "").trim();
        if (!original || !LETTERS.test(original)) return;
        // Skip text we've already handled: our source, or the translation swapped in on hover.
        if (original === el._wzSrc || original === el._wzTranslated) return;
        el._wzSrc = original;

        translate(original)
          .then(function (res) {
            // Text changed mid-translation; bail, the observer re-fires for the new content.
            if ((el.textContent || "").trim() !== original) return;
            el._wzTranslated = res.text.trim();
            var sameLang =
              res.src &&
              res.src.toLowerCase().split("-")[0] === config.target.toLowerCase();
            var unchanged =
              res.text.trim().toLowerCase() === original.toLowerCase();
            if (config.onlyNonTarget && (sameLang || unchanged)) {
              clearTranslation(el);
              return;
            }
            if (unchanged) {
              clearTranslation(el);
              return;
            }
            render(el, original, res.text);
          })
          .catch(function (err) {
            // Endpoint down (bot page / CORS / rate-limit) fails silently otherwise; warn once so it's not mistaken for a dead selector.
            if (!process._warned) { process._warned = true; console.warn("%c[wz-translate]", "color:#30C7FB;font-weight:bold", "translation request failed - the endpoint is likely blocking (bot check / CORS / rate-limit), not the selector:", err); }
            // Network/parse error: allow a retry next time the node is seen.
            if (el._wzSrc === original) el._wzSrc = null;
          });
      }

      function scan(root) {
        if (!root || root.nodeType !== 1) return;
        if (root.matches && root.matches(MSG_SELECTOR)) process(root);
        var nodes = root.querySelectorAll
          ? root.querySelectorAll(MSG_SELECTOR)
          : [];
        for (var i = 0; i < nodes.length; i++) process(nodes[i]);
      }

      // --- observe chat --------------------------------------------------------
      var observer = new MutationObserver(function (mutations) {
        for (var i = 0; i < mutations.length; i++) {
          var m = mutations[i];
          for (var j = 0; j < m.addedNodes.length; j++) scan(m.addedNodes[j]);
          // Text swapped in place (React re-render): re-check the target element.
          if (m.type === "characterData" && m.target.parentNode) {
            var p = m.target.parentNode;
            if (p.matches && p.matches(MSG_SELECTOR)) process(p);
          }
        }
      });
      // Wait for <body>: at document-start (the all-in-one bundle) it isn't parsed yet.
      function observeChat() {
        observer.observe(document.body, {
          childList: true,
          subtree: true,
          characterData: true,
        });
        scan(document.body); // catch messages already on screen
      }
      if (document.body) observeChat();
      else document.addEventListener("DOMContentLoaded", observeChat, { once: true });

      // --- live controls -------------------------------------------------------
      function retranslateAll() {
        var nodes = document.querySelectorAll(MSG_SELECTOR);
        for (var i = 0; i < nodes.length; i++) {
          nodes[i]._wzSrc = null;
          process(nodes[i]);
        }
      }

      // Expose controls on the page window (unsafeWindow) so they're reachable from the DevTools console; under a sandboxed @grant the script's own `window` isn't the page's.
      var pageWindow = typeof unsafeWindow !== "undefined" ? unsafeWindow : window;
      pageWindow.WZTranslate = {
        config: config,
        setMode: function (mode) {
          config.mode = mode;
          // Re-render every message in the new layout.
          var nodes = document.querySelectorAll(MSG_SELECTOR);
          for (var i = 0; i < nodes.length; i++) {
            nodes[i]._wzSrc = null;
            clearTranslation(nodes[i]);
            process(nodes[i]);
          }
        },
        setTarget: function (lang) {
          config.target = lang;
          cache = Object.create(null);
          retranslateAll();
        },
        enable: function () {
          config.enabled = true;
          retranslateAll();
        },
        disable: function () {
          config.enabled = false;
          var nodes = document.querySelectorAll(MSG_SELECTOR);
          for (var i = 0; i < nodes.length; i++) clearTranslation(nodes[i]);
        },
        retranslateAll: retranslateAll,
      };

      console.log(
        "%c[wz-translate] active → " +
          config.target +
          " (mode: " +
          config.mode +
          "). Controls: WZTranslate.setMode('append'|'replace'|'hover')",
        "color:#30C7FB;font-weight:bold",
      );
    })();
  })(PAGE);

  if (menu('spotify', 'Wavez Open in Spotify', 'on')) (function (window) {

    (function () {
      'use strict';

      const log = (...a) => console.log('%c[wz-spotify]', 'color:#1DB954;font-weight:bold', ...a);

      const ID = 'wavez-open-spotify-btn';

      // Drop YouTube descriptor tags in ()/[] ("Official Video", "Lyrics", "HD"). Plain text search beats track:/artist: filters since the artist is a YT channel handle.
      const stripNoise = (s) => (s || '')
        .replace(/[([][^)\]]*\b(officials?|video|audio|lyrics?|visuali[sz]er|m\/?v|hd|4k|remaster(?:ed)?|explicit)\b[^)\]]*[)\]]/gi, '')
        .replace(/\s{2,}/g, ' ')
        .trim();

      function spotifyUrl(titleEl) {
        const pb = window.WavezFM?.version === '1'
          ? window.WavezFM.room.getState()?.playback
          : null;
        const query = stripNoise(pb?.title || titleEl.textContent);
        return 'https://open.spotify.com/search/' + encodeURIComponent(query);
      }

      function addButton() {
        const title = document.querySelector('#wavezfm-current-track-title-desktop');
        const yt = document.querySelector('a[aria-label="Open on YouTube"]');

        if (!title || !yt || document.getElementById(ID)) return;

        const row = title.closest('.flex');
        if (!row) return;

        const wrap = document.createElement('div');
        wrap.className = 'inline-flex shrink-0';
        wrap.id = ID;

        const link = yt.cloneNode(false);
        link.href = '#';
        link.setAttribute('aria-label', 'Open on Spotify');
        link.title = 'Open on Spotify';
        link.style.color = '#ffffff';
        link.style.display = 'inline-flex';
        link.style.visibility = 'visible';
        link.style.opacity = '1';

        link.innerHTML = `
        <svg xmlns="http://www.w3.org/2000/svg"
             width="12"
             height="12"
             viewBox="0 0 24 24"
             fill="currentColor">
          <path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10 10-4.5 10-10S17.55 2 12 2zm3.75 14.65c-2.35-1.45-5.3-1.75-8.8-.95-.35.1-.65-.15-.75-.45-.1-.35.15-.65.45-.75 3.8-.85 7.1-.5 9.7 1.1.35.15.4.55.25.85-.2.3-.55.4-.85.2zm1-2.7c-2.7-1.65-6.8-2.15-9.95-1.15-.4.1-.85-.1-.95-.5-.1-.4.1-.85.5-.95 3.65-1.1 8.15-.55 11.25 1.35.3.15.45.65.2 1s-.7.5-1.05.25zM6.3 9.75c-.5.15-1-.15-1.15-.6-.15-.5.15-1 .6-1.15 3.55-1.05 9.4-.85 13.1 1.35.45.25.6.85.35 1.3-.25.35-.85.5-1.3.25C14.7 9 9.35 8.8 6.3 9.75z"/>
        </svg>
        `;

        link.onclick = (e) => {
          e.preventDefault();
          e.stopPropagation();

          window.open(spotifyUrl(title), '_blank');
        };

        wrap.appendChild(link);

        const titleBox = title.parentElement;
        row.insertBefore(wrap, titleBox);
      }

      setInterval(addButton, 500);

      if (location.hash === '#wz-spotify-test') {
        const cases = [
          ['Groove Is In The Heart (Official Video)', 'Groove Is In The Heart'],
          ['Song [Official Audio]', 'Song'],
          ['Track (Official Music Video) [HD]', 'Track'],
          ['Title (Lyrics)', 'Title'],
          ['Da Funk (Remastered)', 'Da Funk'],
          ['Power (feat. Dwele)', 'Power (feat. Dwele)'], // real parens kept
        ];
        cases.forEach(([raw, want]) =>
          console.assert(stripNoise(raw) === want, 'stripNoise:', raw, '->', stripNoise(raw), 'want', want));
        log('self-check passed');
      }
    })();
  })(PAGE);

  if (menu('chat-toggle', 'Wavez Chat Toggle', 'on')) (function (window) {

    (function () {
      'use strict';

      const KEY = 'wavez-chat-hidden';

      const css = document.createElement('style');
      css.textContent = `
        #wavez-chat-rail-toggle {
          position: fixed;
          top: 50%;
          transform: translateY(-50%);

          width: 20px;
          height: 58px;

          padding: 0;
          border: 1px solid var(--theme-border);
          border-right: 0;
          border-radius: 8px 0 0 8px;

          background: var(--theme-room-nav);
          color: color-mix(in srgb, var(--theme-text-primary) 56%, transparent);

          box-shadow: -8px 0 18px rgba(0,0,0,.22);

          z-index: 2147483647;
          cursor: pointer;

          display: flex;
          align-items: center;
          justify-content: center;

          opacity: .82;
          transition:
            opacity .2s ease,
            color .2s ease,
            background .2s ease;
        }

        #wavez-chat-rail-toggle:hover {
          opacity: 1;
          color: white;
          background: var(--theme-button-neutral-hover);
        }

        #wavez-chat-rail-toggle svg {
          width: 11px;
          height: 11px;
          flex-shrink: 0;
          transition: transform .2s ease;
        }

        #wavez-chat-rail-toggle:hover svg {
          transform: scale(1.12);
        }

        #wavez-chat-rail-toggle.chat-hidden svg {
          transform: rotate(180deg);
        }

        #wavez-chat-rail-toggle.chat-hidden:hover svg {
          transform: rotate(180deg) scale(1.12);
        }

        #wavez-chat-rail-toggle.has-new::after {
          content: '';
          position: absolute;
          top: 6px;
          right: 6px;
          width: 7px;
          height: 7px;
          border-radius: 50%;
          background: var(--theme-accent, #f43f5e);
          box-shadow: 0 0 0 2px var(--theme-room-nav);
        }
      `;
      (document.head || document.documentElement).appendChild(css); // head may be unparsed at document-start (the bundle)

      function getRail() {
        return document.querySelector('[data-room-desktop-rail="true"]');
      }

      function makeButton() {
        const btn = document.createElement('button');
        btn.id = 'wavez-chat-rail-toggle';
        btn.type = 'button';
        btn.setAttribute('aria-label', 'Toggle chat');

        btn.innerHTML = `
          <svg xmlns="http://www.w3.org/2000/svg"
               viewBox="0 0 24 24"
               fill="none"
               stroke="currentColor"
               stroke-width="2.4"
               stroke-linecap="round"
               stroke-linejoin="round">
            <path d="M9 6l6 6l-6 6"></path>
          </svg>
        `;

        document.body.appendChild(btn);
        return btn;
      }

      function init() {
        const rail = getRail();
        if (!rail || document.getElementById('wavez-chat-rail-toggle')) {
          return false;
        }

        const btn = makeButton();

        function apply() {
          const hidden = localStorage.getItem(KEY) === 'true';

          rail.style.display = hidden ? 'none' : '';
          btn.classList.toggle('chat-hidden', hidden);

          // Opening the chat clears the unread dot.
          if (!hidden) btn.classList.remove('has-new');

          if (hidden) {
            btn.style.right = '0px';
          } else {
            const rect = rail.getBoundingClientRect();

            // Makes the handle stick out slightly from the chat rail
            btn.style.right = `${window.innerWidth - rect.left - 1}px`;
          }
        }

        btn.addEventListener('click', () => {
          const hidden = localStorage.getItem(KEY) === 'true';
          localStorage.setItem(KEY, String(!hidden));
          apply();
        });

        window.addEventListener('resize', apply);

        // Flag an unread dot when a message arrives while chat is hidden.
        const markUnread = () => {
          if (localStorage.getItem(KEY) === 'true') btn.classList.add('has-new');
        };

        const api = window.WavezFM;
        if (api && api.version === '1') {
          // Bridge fires only on real chat messages - no false positives from unrelated rail DOM churn.
          api.room.subscribe('chat_message', markUnread);
        } else {
          new MutationObserver((records) => {
            if (records.some((r) => r.addedNodes.length)) markUnread();
          }).observe(rail, { childList: true, subtree: true });
        }

        apply();
        return true;
      }

      const wait = setInterval(() => {
        if (init()) {
          clearInterval(wait);
        }
      }, 500);
    })();
  })(PAGE);

  if (menu('chat-popout', 'Wavez Chat Pop-out', 'on')) (function (window) {

    (function () {
      'use strict';

      // Grab a handle to the live socket so we can send (reading is done by mirroring the rail DOM). Wraps message listeners only, never the constructor.
      let socket = null;
      let reqN = 0;

      function tap(e) {
        if (typeof e.data !== 'string') return;
        let b;
        try { b = JSON.parse(e.data); } catch { return; }
        if (!b || b.version !== 'v1') return;
        socket = e.target; // this is the wavez socket
      }

      const addEL = WebSocket.prototype.addEventListener;
      WebSocket.prototype.addEventListener = function (type, listener, ...rest) {
        if (type === 'message' && typeof listener === 'function') {
          const wrapped = function (e) { tap(e); return listener.apply(this, arguments); };
          return addEL.call(this, type, wrapped, ...rest);
        }
        return addEL.call(this, type, listener, ...rest);
      };

      const desc = Object.getOwnPropertyDescriptor(WebSocket.prototype, 'onmessage');
      if (desc && desc.set) {
        Object.defineProperty(WebSocket.prototype, 'onmessage', {
          configurable: true,
          get() { return desc.get.call(this); },
          set(fn) {
            if (typeof fn === 'function') {
              const wrapped = function (e) { tap(e); return fn.apply(this, arguments); };
              desc.set.call(this, wrapped);
            } else {
              desc.set.call(this, fn);
            }
          },
        });
      }

      function send(content) {
        content = content.trim();
        if (!content || !socket || socket.readyState !== 1) return false;
        socket.send(JSON.stringify({
          type: 'command',
          event: 'send_chat',
          requestId: `req-${++reqN}-${Date.now()}`,
          version: 'v1',
          timestamp: new Date().toISOString(),
          payload: { content, channel: 'public', replyTo: null },
        }));
        return true;
      }

      // Popup window with a custom chat UI (blank same-origin window => no session).
      let popup = null;

      // Copy the page's stylesheets into the popup so theme vars, font and scrollbars are the live ones; our markup just references var(--theme-*).
      function copyStyles(win) {
        for (const sheet of document.styleSheets) {
          try {
            const rules = [...sheet.cssRules].map((r) => r.cssText).join('\n');
            const style = win.document.createElement('style');
            style.textContent = rules;
            win.document.head.appendChild(style);
          } catch {
            if (sheet.href) {
              const link = win.document.createElement('link');
              link.rel = 'stylesheet';
              link.href = sheet.href;
              win.document.head.appendChild(link);
            }
          }
        }
      }

      // Our layout, loaded after the page sheets so it wins; colors/fonts pull from the copied --theme-* vars (fallbacks cover a cold load).
      const popupCss = () => `
        :root { color-scheme: dark; }
        * { box-sizing: border-box; }
        html, body { margin: 0; height: 100%; }
        body {
          display: flex; flex-direction: column;
          background: var(--theme-room-nav, #16181c);
          color: var(--theme-text-primary, #e7e9ea);
          font: 14px/1.4 var(--theme-font, system-ui, -apple-system, Segoe UI, sans-serif);
        }
        #wz-head {
          flex: 0 0 auto; display: flex; align-items: center; gap: 8px;
          padding: 10px 12px; font-weight: 700; font-size: 13px; letter-spacing: .02em;
          border-bottom: 1px solid var(--theme-border, #2a2d33);
          background: var(--theme-room-nav, #16181c);
        }
        #wz-head svg { width: 15px; height: 15px; opacity: .7; }
        #wz-list { flex: 1 1 auto; overflow-y: auto; padding: 10px; }
        #wz-bar { flex: 0 0 auto; display: flex; gap: 6px; padding: 8px; border-top: 1px solid var(--theme-border, #2a2d33); }
        #wz-input {
          flex: 1 1 auto; resize: none; height: 38px; padding: 9px 10px;
          background: var(--theme-background, #0f1115); color: var(--theme-text-primary, #e7e9ea);
          border: 1px solid var(--theme-border, #2a2d33); border-radius: 8px;
          font: inherit;
        }
        #wz-send {
          flex: 0 0 auto; padding: 0 14px; border: 0; border-radius: 8px; cursor: pointer;
          background: var(--theme-accent, #1d9bf0); color: #fff; font-weight: 600;
        }
        #wz-send:hover { filter: brightness(1.1); }
        #wz-offline { padding: 6px 10px; font-size: 12px; color: var(--theme-accent, #f43f5e); display: none; }
        body.wz-offline #wz-offline { display: block; }
        body.wz-offline #wz-send { opacity: .5; pointer-events: none; }
      `;

      function openPopup() {
        if (popup && !popup.closed) { popup.focus(); return; }

        popup = window.open('', 'wavezChat', 'popup,width=380,height=640');
        if (!popup) { alert('Popup blocked - allow popups for wavez.fm.'); return; }

        const d = popup.document;
        d.title = 'Wavez Chat';
        d.head.innerHTML = '<meta charset="utf-8">';
        copyStyles(popup);
        const own = d.createElement('style');
        own.textContent = popupCss();
        d.head.appendChild(own);
        d.body.innerHTML = `
          <div id="wz-head">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
            </svg>
            <span>Chat</span>
          </div>
          <div id="wz-list"></div>
          <div id="wz-offline">Reconnecting… messages can't be sent right now.</div>
          <div id="wz-bar">
            <textarea id="wz-input" placeholder="Message…" rows="1"></textarea>
            <button id="wz-send" type="button">Send</button>
          </div>
        `;

        const list = d.getElementById('wz-list');
        const input = d.getElementById('wz-input');

        // Mirror the rail's message nodes verbatim; the copied stylesheets style the clones, so it's pixel-identical.
        function railList() {
          const rail = document.querySelector('[data-room-desktop-rail="true"]');
          if (!rail) return null;
          let el = rail.querySelector('[class*="wavezfm-chat-text-size"]'); // a message body
          while (el && el !== rail) {
            const oy = getComputedStyle(el).overflowY;
            if (oy === 'auto' || oy === 'scroll') return el; // the scroll container
            el = el.parentElement;
          }
          return null;
        }

        function clone(node) {
          if (node.nodeType !== 1) return; // elements only
          const atBottom = list.scrollHeight - list.scrollTop - list.clientHeight < 40;
          list.appendChild(d.importNode(node, true));
          if (atBottom) list.scrollTop = list.scrollHeight;
        }

        let mo = null;
        (function attach() {
          if (!popup || popup.closed) return;
          const src = railList();
          if (!src) { popup.setTimeout(attach, 300); return; } // wait for chat to render
          for (const child of src.children) clone(child);
          list.scrollTop = list.scrollHeight;
          mo = new MutationObserver((muts) => {
            for (const mu of muts) mu.addedNodes.forEach(clone);
          });
          mo.observe(src, { childList: true });
        })();

        function syncState() {
          d.body.classList.toggle('wz-offline', !socket || socket.readyState !== 1);
        }
        const stateTimer = popup.setInterval(syncState, 1000);
        syncState();

        function submit() {
          if (send(input.value)) { input.value = ''; input.style.height = '38px'; }
        }
        d.getElementById('wz-send').addEventListener('click', submit);
        input.addEventListener('keydown', (ev) => {
          if (ev.key === 'Enter' && !ev.shiftKey) { ev.preventDefault(); submit(); }
        });
        input.focus();

        popup.addEventListener('pagehide', () => {
          if (mo) mo.disconnect();
          popup.clearInterval(stateTimer);
        });
      }

      // Pop-out button (added once the page DOM exists).
      const BTN_CSS = `
        #wavez-chat-popout-btn {
          position: fixed; right: 0; top: 50%; transform: translateY(-50%); margin-top: -64px;
          width: 20px; height: 58px; padding: 0;
          border: 1px solid var(--theme-border, #333); border-right: 0; border-radius: 8px 0 0 8px;
          background: var(--theme-room-nav, #1a1a1a);
          color: color-mix(in srgb, var(--theme-text-primary, #eee) 56%, transparent);
          box-shadow: -8px 0 18px rgba(0,0,0,.22);
          z-index: 2147483646; cursor: pointer;
          display: flex; align-items: center; justify-content: center;
          opacity: .82; transition: opacity .2s ease, color .2s ease, background .2s ease;
        }
        #wavez-chat-popout-btn:hover { opacity: 1; color: #fff; background: var(--theme-button-neutral-hover, #2a2a2a); }
        #wavez-chat-popout-btn svg { width: 12px; height: 12px; }
      `;

      function addButton() {
        if (document.getElementById('wavez-chat-popout-btn')) return;
        const style = document.createElement('style');
        style.textContent = BTN_CSS;
        document.head.appendChild(style);

        const btn = document.createElement('button');
        btn.id = 'wavez-chat-popout-btn';
        btn.type = 'button';
        btn.setAttribute('aria-label', 'Pop out chat');
        btn.innerHTML = `
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"
               stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M15 3h6v6"></path><path d="M10 14L21 3"></path>
            <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path>
          </svg>
        `;
        btn.addEventListener('click', openPopup);
        document.body.appendChild(btn);
      }

      if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', addButton);
      } else {
        addButton();
      }
    })();
  })(PAGE);

  if (menu('imgur', 'Wavez Imgur -> Rimgo Safe', 'on')) (function (window) {

    (function () {
      'use strict';

      const ALTSITE = 'https://rimgo.vern.cc';

      function rewrite(value) {
        if (!value || !value.includes('imgur.com')) return value;

        return value.replace(
          /https?:\/\/(?:i\.|m\.|www\.)?imgur\.com/gi,
          ALTSITE
        );
      }

      // nicewoot measures the imgur image (new Image()) to size its avatar sprites, so a region-blocked browser measures the placeholder and the geometry is wrong however we rewrite the DOM. Rewrite at the src boundary so the measurement loads Rimgo. Needs document-start.
      function patchImageSrc() {
        const proto = HTMLImageElement.prototype;
        for (const prop of ['src', 'srcset']) {
          const desc = Object.getOwnPropertyDescriptor(proto, prop);
          if (!desc || !desc.set) continue;
          Object.defineProperty(proto, prop, {
            configurable: true,
            enumerable: desc.enumerable,
            get() { return desc.get.call(this); },
            set(v) { desc.set.call(this, rewrite(v)); }
          });
        }
        // Also the setAttribute path.
        const setAttr = proto.setAttribute;
        proto.setAttribute = function (name, value) {
          if (name === 'src' || name === 'srcset') value = rewrite(value);
          return setAttr.call(this, name, value);
        };
      }
      try { patchImageSrc(); } catch (e) {}

      function fixElement(el) {
        if (!el || el.nodeType !== 1) return;

        for (const attr of ['href', 'src', 'srcset', 'data-src', 'poster', 'style']) {
          const oldValue = el.getAttribute(attr);
          if (!oldValue || !oldValue.includes('imgur.com')) continue;

          const newValue = rewrite(oldValue);
          if (newValue !== oldValue) {
            el.setAttribute(attr, newValue);
          }
        }
      }

      // Badges live in an injected <style> block (--nw-badge-img: url(...)), not an attribute, so rewrite the stylesheet text too.
      function fixStyleEl(el) {
        if (!el || el.tagName !== 'STYLE') return;

        const css = el.textContent;
        if (!css || !css.includes('imgur.com')) return;

        const next = rewrite(css);
        if (next !== css) el.textContent = next;
      }

      // insertRule() rules have no <style> text node, so rewrite them in the CSSOM. Recurse into @media/@layer/@supports.
      function fixRules(parent) {
        let rules;
        try {
          rules = parent.cssRules;
        } catch (e) {
          return; // cross-origin sheet, not readable
        }
        if (!rules) return;

        for (let i = 0; i < rules.length; i++) {
          const rule = rules[i];

          // Grouping rule - descend.
          if (rule.cssRules && rule.cssRules.length) {
            fixRules(rule);
            continue;
          }

          const text = rule.cssText;
          if (!text || !text.includes('imgur.com')) continue;

          const next = rewrite(text);
          if (next === text) continue;

          try {
            parent.deleteRule(i);
            parent.insertRule(next, i);
          } catch (e) {
            // malformed rule - skip
          }
        }
      }

      function fixSheets(root) {
        let sheets = [];
        // <style> + <link>, plus constructed adoptedStyleSheets.
        try {
          if (root.styleSheets) sheets = sheets.concat(Array.from(root.styleSheets));
        } catch (e) {}
        try {
          if (root.adoptedStyleSheets) sheets = sheets.concat(Array.from(root.adoptedStyleSheets));
        } catch (e) {}
        sheets.forEach(fixRules);
      }

      function scanStyles(root) {
        root = root || document;
        root.querySelectorAll?.('style').forEach(fixStyleEl);
        fixSheets(root);
      }

      // The niceatc badge sheet is cross-origin, so the CSSOM won't read it. Refetch it, rewrite the raw CSS, inject as a local <style>, and disable the original <link>. Needs GM_xmlhttpRequest + @connect.
      const REMOTE_CSS_HOST = 'niceatc';
      const remoteCss = new Map(); // href -> 'pending' | 'done' | 'clean' | 'failed'

      function gmFetch() {
        if (typeof GM_xmlhttpRequest !== 'undefined') return GM_xmlhttpRequest;
        if (typeof GM !== 'undefined' && GM.xmlHttpRequest) return GM.xmlHttpRequest;
        return null;
      }

      function importRemoteCss(link) {
        const href = link.href;
        if (!href) return;

        let url;
        try { url = new URL(href, location.href); } catch (e) { return; }
        if (url.origin === location.origin) return;          // same-origin = readable elsewhere
        if (!url.hostname.includes(REMOTE_CSS_HOST)) return; // only the niceatc sheet

        const state = remoteCss.get(href);
        if (state === 'done') { link.disabled = true; return; } // keep replacements disabled
        if (state) return;                                      // pending / clean / failed

        const fetcher = gmFetch();
        if (!fetcher) return; // no cross-origin read available (script needs @grant)

        remoteCss.set(href, 'pending');
        fetcher({
          method: 'GET',
          url: href,
          onload(res) {
            const css = res.responseText || '';
            if (!css.includes('imgur.com')) { remoteCss.set(href, 'clean'); return; }
            const style = document.createElement('style');
            style.setAttribute('data-rimgo-import', href);
            style.textContent = rewrite(css);
            (document.head || document.documentElement).appendChild(style);
            link.disabled = true;
            remoteCss.set(href, 'done');
          },
          onerror() { remoteCss.set(href, 'failed'); }
        });
      }

      function scanRemoteCss() {
        document.querySelectorAll('link[rel~="stylesheet"]').forEach(importRemoteCss);
      }

      function scan(root) {
        if (!root) return;

        if (root.nodeType === 1) {
          fixElement(root);
          fixStyleEl(root);
        }

        root.querySelectorAll?.('[href*="imgur.com"], [src*="imgur.com"], [srcset*="imgur.com"], [data-src*="imgur.com"], [poster*="imgur.com"], [style*="imgur.com"]')
          .forEach(fixElement);

        root.querySelectorAll?.('style').forEach(fixStyleEl);

        // Descend into shadow roots.
        root.querySelectorAll?.('*').forEach(el => {
          if (el.shadowRoot) {
            scan(el.shadowRoot);
            scanStyles(el.shadowRoot);
          }
        });
      }

      function fullScan() {
        scan(document.body);
        scanStyles();
        scanRemoteCss();
      }

      function start() {
        // Attach at document-start, before nicewoot mounts avatars, so their imgur URLs are rewritten before the browser fetches the placeholder.
        const observer = new MutationObserver(mutations => {
          for (const mutation of mutations) {
            if (mutation.type === 'childList') {
              mutation.addedNodes.forEach(scan);
            }

            if (mutation.type === 'attributes') {
              fixElement(mutation.target);
            }
          }
        });

        // Observe <html> so injected <head> <style> blocks are caught too.
        observer.observe(document.documentElement, {
          childList: true,
          subtree: true,
          attributes: true,
          attributeFilter: ['href', 'src', 'srcset', 'data-src', 'poster', 'style']
        });

        // Sweep now, again once the body parses, then a slow fallback.
        fullScan();
        if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', fullScan);
        setInterval(fullScan, 1500);
      }

      start();
    })();
  })(PAGE);

  if (menu('scrobble', 'Wavez Scrobble Toggle', 'on')) (function (window) {

    (function () {
      var API = "https://api.wavez.fm/settings";
      var state = null; // null until first read
      var busy = false;
      var btn = null;

      function read(body) {
        if (body && typeof body.lastFmScrobblingEnabled === "boolean") state = body.lastFmScrobblingEnabled;
        return state;
      }

      function getState() {
        return fetch(API, { credentials: "include" }).then(function (r) { return r.json(); }).then(read);
      }

      function setState(v) {
        return fetch(API, {
          method: "PATCH",
          credentials: "include",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({ lastFmScrobblingEnabled: v }),
        }).then(function (r) { if (!r.ok) throw new Error("PATCH " + r.status); return r.json(); }).then(read);
      }

      function toggle() {
        if (busy) return;
        busy = true;
        render();
        var ready = state === null ? getState() : Promise.resolve(state);
        ready
          .then(function (cur) { return setState(!cur); })
          .catch(function () { state = null; })
          .then(function () { busy = false; render(); });
      }

      function render() {
        if (!btn || !btn.isConnected) return;
        var on = state === true, off = state === false;
        var label = busy ? "Scrobbling…" : "Last.fm scrobbling: " + (on ? "on" : off ? "off" : "unknown");
        btn.title = label;
        btn.setAttribute("aria-label", label);
        btn.style.opacity = busy ? "0.6" : "1";
        if (on) { btn.style.borderColor = "rgba(52,211,153,.26)"; btn.style.background = "rgba(16,185,129,.10)"; btn.style.color = "#d1fae5"; }
        else if (off) { btn.style.borderColor = "rgba(248,113,113,.26)"; btn.style.background = "rgba(239,68,68,.10)"; btn.style.color = "#fee2e2"; }
        else { btn.style.borderColor = ""; btn.style.background = ""; btn.style.color = "rgba(255,255,255,.4)"; }
      }

      // State colour is inline so it renders without Tailwind JIT.
      function build() {
        var wrap = document.createElement("div");
        wrap.className = "inline-flex";
        wrap.innerHTML =
          '<button id="wz-scrobble-btn" type="button" data-wavezfm-room-footer-action="scrobble" class="relative inline-flex h-8 w-8 items-center justify-center rounded-md border leading-none transition xl:h-9 xl:w-9 hover:border-(--theme-field-border-focus) hover:bg-(--theme-button-neutral-hover)">' +
          '<span class="pointer-events-none relative z-10 inline-flex h-full w-full items-center justify-center leading-none [&>svg]:block [&>svg]:shrink-0">' +
          '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="tabler-icon tabler-icon-radio">' +
          '<path d="M14 3l-9.371 3.749a1 1 0 0 0 -.629 .928v11.323a1 1 0 0 0 1 1h14a1 1 0 0 0 1 -1v-11a1 1 0 0 0 -1 -1h-14.5"></path><path d="M4 12h16"></path><path d="M7 12v-2"></path><path d="M17 16v.01"></path><path d="M13 16v.01"></path>' +
          "</svg></span></button>";
        btn = wrap.firstChild;
        btn.addEventListener("click", toggle);
        return wrap;
      }

      // The wrapper div, not the button (it also has inline-flex).
      function discordWrap() {
        var btns = document.querySelectorAll('button[aria-label="Discord"]');
        for (var i = 0; i < btns.length; i++) {
          if (btns[i].offsetParent === null) continue;
          var w = btns[i].closest("div.inline-flex");
          if (w && w.parentElement) return w;
        }
        return null;
      }

      // Sit after Discord; re-add if the SPA re-renders the row away.
      function ensure() {
        if (document.getElementById("wz-scrobble-btn")) return;
        var anchor = discordWrap();
        if (!anchor) return;
        anchor.after(build());
        render();
        if (state === null) getState().then(render).catch(function () {});
      }

      new MutationObserver(ensure).observe(document.documentElement, { childList: true, subtree: true });
      ensure();

      if (typeof GM_registerMenuCommand === "function") GM_registerMenuCommand("Toggle Last.fm scrobbling", toggle);
    })();
  })(PAGE);

  if (menu('auto-woot', 'Wavez Auto Woot', 'off')) (function (window) {

    // Uses the official extension API: https://github.com/WavezFM/WavezFM-Extension-API
    (function () {
      'use strict';

      var log = function () { console.log.apply(console, ["%c[wz-woot]", "color:#EF5350;font-weight:bold"].concat([].slice.call(arguments))); };
      var warn = function () { console.warn.apply(console, ["%c[wz-woot]", "color:#EF5350;font-weight:bold"].concat([].slice.call(arguments))); };

      var enabled = localStorage.getItem('wavez-autowoot') !== 'off';
      var lastKey = null;

      // New track, not already wooted, voting allowed. playbackKey = track-change signal, clientVote = our vote.
      function shouldVote(key, last, votes) {
        return !!key && key !== last && !!votes && votes.canVote && votes.clientVote !== 'woot';
      }

      function voteCurrent(api) {
        if (!enabled) return;
        var state = api.room.getState();
        var pb = state && state.playback;
        if (!pb) return;
        // Stamp lastKey only on an actual vote, else a not-yet-votable track gets marked handled and never retried (the background-tab miss).
        if (!shouldVote(pb.playbackKey, lastKey, state.votes)) return;
        lastKey = pb.playbackKey;
        var res = api.actions.vote('woot');
        if (!res || !res.ok) warn('vote failed:', res && res.code);
      }

      function init(api) {
        voteCurrent(api); // catch the track already playing at load
        api.room.subscribe('playback_changed', function () { voteCurrent(api); });
        // Retry once the vote state actually arrives for the new track.
        api.room.subscribe('votes_changed', function () { voteCurrent(api); });
        // Backstop for a hidden tab where events get missed/throttled; shouldVote gates it, so re-checking is free.
        setInterval(function () { voteCurrent(api); }, 30000);

        window.WZWoot = {
          now: function () { lastKey = null; voteCurrent(api); }, // force a woot
          on: function () { enabled = true; localStorage.setItem('wavez-autowoot', 'on'); voteCurrent(api); },
          off: function () { enabled = false; localStorage.setItem('wavez-autowoot', 'off'); },
          get enabled() { return enabled; }
        };
        log('auto-woot ' + (enabled ? 'on' : 'off') + ' - toggle with WZWoot.on() / WZWoot.off()');
      }

      // The bridge may be injected after document-idle, so wait for it.
      var tries = 0;
      var wait = setInterval(function () {
        var api = window.WavezFM;
        if (api && api.version === '1') {
          clearInterval(wait);
          init(api);
        } else if (++tries > 40) {
          clearInterval(wait); // ~20s, give up quietly (not in a room, or API gone)
        }
      }, 500);

      // Quick check on the vote guard: load with #wz-woot-test.
      if (location.hash === '#wz-woot-test') {
        var ok = { canVote: true, clientVote: null };
        console.assert(shouldVote('k1', null, ok) === true, 'new track, can vote');
        console.assert(shouldVote('k1', 'k1', ok) === false, 'same track, skip');
        console.assert(shouldVote('k2', 'k1', { canVote: false, clientVote: null }) === false, 'cannot vote, skip');
        console.assert(shouldVote('k2', 'k1', { canVote: true, clientVote: 'woot' }) === false, 'already wooted, skip');
        console.assert(shouldVote(null, 'k1', ok) === false, 'no playbackKey, skip');
        log('tests passed');
      }
    })();
  })(PAGE);

  if (menu('auto-grab', 'Wavez Auto Grab', 'off')) (function (window) {

    // Track state comes from the extension API (github.com/WavezFM/WavezFM-Extension-API), but grab isn't an exposed action, so we click the real button and pick from the picker.
    (function () {
      'use strict';

      // Playlist to grab into, by name. "" = whichever the picker lists first.
      var PLAYLIST = 'Recs';

      // Only set these if the heuristics below match the wrong element. Run WZGrab.debug() in the console to see what they currently find.
      var GRAB_BTN_SELECTOR = '';
      var PICKER_SELECTOR = '';

      var LS_KEY = 'wavez-autograb';
      // Default off: unlike a woot, a grab writes to your playlist.
      var enabled = localStorage.getItem(LS_KEY) === 'on';
      var lastKey = null;

      var log = function () { console.log.apply(console, ["%c[wz-grab]", "color:#FFCA28;font-weight:bold"].concat([].slice.call(arguments))); };
      var warn = function () { console.warn.apply(console, ["%c[wz-grab]", "color:#FFCA28;font-weight:bold"].concat([].slice.call(arguments))); };

      // Grab once, after you woot. playbackKey = track, clientVote = your vote (manual or auto-woot), clientGrabbed = already in a playlist.
      function shouldGrab(key, last, votes) {
        return !!key && key !== last && !!votes &&
          votes.clientVote === 'woot' && !votes.clientGrabbed;
      }

      // ---------------------------------- dom ----------------------------------
      function visible(el) {
        return el.offsetParent !== null;
      }

      // Vote buttons have no aria-label/id. Anchor on the --theme-vote-grab count span (survives relabels/locales), falling back to the "Grab" label span.
      function findGrabButton() {
        if (GRAB_BTN_SELECTOR) return document.querySelector(GRAB_BTN_SELECTOR);
        var btns = document.querySelectorAll('button');
        var byLabel = null;
        for (var i = 0; i < btns.length; i++) {
          if (btns[i].querySelector('[style*="theme-vote-grab"]')) return btns[i];
          if (byLabel) continue;
          // Match the label span exactly: the button's own textContent reads "Grab0".
          var spans = btns[i].querySelectorAll('span');
          for (var j = 0; j < spans.length; j++) {
            if (spans[j].textContent.trim().toLowerCase() === 'grab') { byLabel = btns[i]; break; }
          }
        }
        return byLabel;
      }

      // The picker has no role/dialog attrs, only data-wavezfm-grab-menu-root (shared with the Grab button's wrapper). It's the one NOT containing the button, and only exists while open.
      function findPicker() {
        if (PICKER_SELECTOR) return document.querySelector(PICKER_SELECTOR);
        var btn = findGrabButton();
        var roots = document.querySelectorAll('[data-wavezfm-grab-menu-root]');
        for (var i = 0; i < roots.length; i++) {
          if (btn && roots[i].contains(btn)) continue; // that's the wrapper
          if (visible(roots[i])) return roots[i];
        }
        return null;
      }

      // An option's textContent runs the name into the subtitle ("RecsPlaylist - 53/300"), so read the name span instead.
      function nameOf(el) {
        var span = el.querySelector('span.truncate');
        return (span ? span.textContent : el.textContent).trim();
      }

      // The second truncate span, e.g. "Active - 58/300" or "Playlist - 53/300".
      function detailOf(el) {
        var spans = el.querySelectorAll('span.truncate');
        return spans.length > 1 ? spans[1].textContent.trim() : '';
      }

      // Every playlist button in the open picker. Full playlists come back too, but disabled - callers decide whether to care.
      function optionsIn(picker) {
        var items = picker.querySelectorAll('button');
        var out = [];
        for (var i = 0; i < items.length; i++) {
          if (items[i].getAttribute('aria-label') === 'Cancel') continue; // header close
          if (visible(items[i])) out.push(items[i]);
        }
        return out;
      }

      function closePicker(picker) {
        var cancel = picker.querySelector('[aria-label="Cancel"]');
        if (cancel) cancel.click();
      }

      // Open the picker if needed, pass options to cb, and report if we opened it so the caller can close it.
      function withPicker(cb) {
        var open = findPicker();
        if (open) return cb(optionsIn(open), null);
        var btn = findGrabButton();
        if (!btn) { log('grab button not found - are you in a room?'); return cb([], null); }
        btn.click();
        waitFor(findPicker, 2000, function (picker) {
          if (!picker) { log('picker did not open'); return cb([], null); }
          cb(optionsIn(picker), picker);
        });
      }

      // Poll for fn() to go truthy, up to ms. The picker opens asynchronously.
      function waitFor(fn, ms, cb) {
        var waited = 0;
        var t = setInterval(function () {
          var v = fn();
          if (v) { clearInterval(t); cb(v); }
          else if ((waited += 100) >= ms) { clearInterval(t); cb(null); }
        }, 100);
      }

      function choosePlaylist(picker) {
        // Full playlists (300/300) come through disabled, so they can't be grabbed into.
        var options = optionsIn(picker).filter(function (el) { return !el.disabled; });
        if (!options.length) { log('picker opened but listed no playlists'); return; }

        var pick = options[0];
        if (PLAYLIST) {
          pick = options.filter(function (el) {
            return nameOf(el).toLowerCase() === PLAYLIST.toLowerCase();
          })[0];
          if (!pick) {
            log('playlist "' + PLAYLIST + '" not in the picker (full or renamed?), skipping');
            return;
          }
        }
        pick.click();
        log('grabbed into "' + nameOf(pick) + '"');
      }

      function doGrab() {
        var btn = findGrabButton();
        if (!btn) { log('grab button not found - set GRAB_BTN_SELECTOR'); return; }
        btn.click();
        waitFor(findPicker, 2000, function (picker) {
          if (!picker) { log('no picker appeared, assuming the grab went straight through'); return; }
          choosePlaylist(picker);
        });
      }

      function grabCurrent(api) {
        if (!enabled) return;
        var state = api.room.getState();
        var pb = state && state.playback;
        if (!pb) return;
        // Stamp lastKey only on an actual grab, else the pre-woot window dedupes the track away.
        if (!shouldGrab(pb.playbackKey, lastKey, state.votes)) return;
        lastKey = pb.playbackKey;
        doGrab();
      }

      // ----------------------------------- ui ----------------------------------
      function buildUI(api) {
        var css = document.createElement('style');
        css.textContent =
          '#wz-grab-pill{position:fixed;right:14px;bottom:14px;z-index:99999;' +
          'display:flex;gap:6px;align-items:center;padding:7px 12px;border-radius:999px;' +
          'background:rgba(20,20,26,.86);border:1px solid rgba(255,255,255,.12);' +
          'font:500 12px/1 system-ui,sans-serif;color:#e7e7ea;cursor:pointer;user-select:none;opacity:.6}' +
          '#wz-grab-pill.on{opacity:1}' +
          '#wz-grab-pill input{accent-color:#ff5c8a;margin:0;cursor:pointer}';
        document.head.appendChild(css);

        var pill = document.createElement('label');
        pill.id = 'wz-grab-pill';
        pill.title = 'Grab a track into "' + (PLAYLIST || 'the first playlist') + '" whenever you woot it';
        if (enabled) pill.className = 'on';

        var box = document.createElement('input');
        box.type = 'checkbox';
        box.checked = enabled;
        box.addEventListener('change', function () {
          enabled = box.checked;
          localStorage.setItem(LS_KEY, enabled ? 'on' : 'off');
          pill.className = enabled ? 'on' : '';
          if (enabled) grabCurrent(api);
        });

        pill.appendChild(box);
        pill.appendChild(document.createTextNode('auto grab'));
        document.body.appendChild(pill);
      }

      // ---------------------------------- init ---------------------------------
      function init(api) {
        grabCurrent(api); // catch a track that's already wooted at load
        // The woot is the trigger, so watch votes, not playback.
        api.room.subscribe('votes_changed', function () { grabCurrent(api); });
        buildUI(api);

        window.WZGrab = {
          on: function () { enabled = true; localStorage.setItem(LS_KEY, 'on'); grabCurrent(api); },
          off: function () { enabled = false; localStorage.setItem(LS_KEY, 'off'); },
          now: function () { lastKey = null; doGrab(); }, // force a grab
          get enabled() { return enabled; },
          // Print your playlist names for PLAYLIST. Opens/reads/closes the picker (opening doesn't grab); async, prints once rendered.
          playlists: function () {
            withPicker(function (options, opened) {
              if (options.length) {
                console.table(options.map(function (el) {
                  return {
                    playlist: nameOf(el),
                    detail: detailOf(el),
                    full: !!el.disabled,
                    target: nameOf(el).toLowerCase() === PLAYLIST.toLowerCase()
                  };
                }));
              }
              if (opened) closePicker(opened);
            });
          },
          // What the heuristics currently match, for pinning the selectors.
          debug: function () {
            console.log('grab button:', findGrabButton());
            console.log('picker (open it first):', findPicker());
          }
        };
        log('auto grab ' + (enabled ? 'on' : 'off') + ' - toggle with the corner pill or WZGrab.on()/off()');
      }

      // The bridge may arrive after document-idle, so wait for it. Logged up front so a missing bridge is distinguishable from a missing script.
      log('loaded, waiting for the WavezFM bridge...');
      var tries = 0;
      var wait = setInterval(function () {
        var api = window.WavezFM;
        if (api && api.version === '1') {
          clearInterval(wait);
          init(api);
        } else if (++tries > 40) { // ~20s
          clearInterval(wait);
          warn('WavezFM bridge never appeared, so WZGrab is unavailable. Are you inside a room? window.WavezFM is currently ' + typeof window.WavezFM + '.');
        }
      }, 500);

      if (location.hash === '#wz-grab-test') {
        var wooted = { clientVote: 'woot', clientGrabbed: false };
        console.assert(shouldGrab('k1', null, wooted) === true, 'wooted, not grabbed');
        console.assert(shouldGrab('k1', 'k1', wooted) === false, 'already grabbed this track, skip');
        console.assert(shouldGrab('k2', 'k1', { clientVote: null, clientGrabbed: false }) === false, 'not wooted yet, skip');
        console.assert(shouldGrab('k2', 'k1', { clientVote: 'meh', clientGrabbed: false }) === false, 'mehed, skip');
        console.assert(shouldGrab('k2', 'k1', { clientVote: 'woot', clientGrabbed: true }) === false, 'already in a playlist, skip');
        console.assert(shouldGrab(null, 'k1', wooted) === false, 'no playbackKey, skip');
        log('tests passed');
      }
    })();
  })(PAGE);

  if (menu('region-check', 'Wavez Region Check', 'off')) (function (window) {

    (function () {
      'use strict';

      // A track is flagged when its allowed list is a subset of these.
      var REGIONS = ['US', 'CA'];

      // YouTube Data API v3 key. Leave blank to be prompted on first run (then remembered).
      var YT_API_KEY = '';

      var API = 'https://api.wavez.fm';
      var KEY_LS = 'wavez-region-ytkey';
      var FLAGS_LS = 'wavez-region-flags-v1'; // persisted flags, to restore pills on load
      var YT = 'https://www.googleapis.com/youtube/v3/videos';

      // normTitle -> count, so rows can be tagged as the list re-renders. Title is all we can match on: rows carry no track id.
      var lockedTitles = {};
      var lastOffenders = []; // from the last check, for the console remove helpers

      var log = function () { console.log.apply(console, ["%c[wz-region]", "color:#9CCC65;font-weight:bold"].concat([].slice.call(arguments))); };

      // Snoop the app's own Authorization header off its requests and reuse it, since we can't guess it.
      var authHeader = null;
      (function captureAuth() {
        var of = window.fetch;
        window.fetch = function (input, init) {
          try {
            var url = typeof input === 'string' ? input : (input && input.url) || '';
            if (url.indexOf('api.wavez.fm') !== -1) {
              var h = new Headers((init && init.headers) || (typeof input === 'object' && input.headers) || {});
              var a = h.get('authorization');
              if (a) authHeader = a;
            }
          } catch (e) {}
          return of.apply(this, arguments);
        };
      })();

      function apiKey() {
        var k = YT_API_KEY || localStorage.getItem(KEY_LS) || '';
        if (!k) {
          k = (window.prompt('YouTube Data API key (stored in localStorage, only used for videos.list):') || '').trim();
          if (k) localStorage.setItem(KEY_LS, k);
        }
        return k;
      }

      function apiGet(path) {
        var headers = {};
        if (authHeader) headers['Authorization'] = authHeader;
        return fetch(API + path, { credentials: 'include', headers: headers }).then(function (res) {
          if (!res.ok) throw new Error(path + ' -> ' + res.status);
          return res.json();
        }).then(function (j) {
          return Array.isArray(j) ? j : (j && j.data) || []; // bare array today, tolerate a data envelope
        });
      }

      function apiDelete(path) {
        var headers = {};
        if (authHeader) headers['Authorization'] = authHeader;
        return fetch(API + path, { method: 'DELETE', credentials: 'include', headers: headers }).then(function (res) {
          if (!res.ok) throw new Error('DELETE ' + path + ' -> ' + res.status);
          return true;
        });
      }

      function readJSON(lsKey) {
        try { return JSON.parse(localStorage.getItem(lsKey)) || null; } catch (e) { return null; }
      }
      function writeJSON(lsKey, obj) {
        try { localStorage.setItem(lsKey, JSON.stringify(obj)); } catch (e) {}
      }

      function saveFlags() { writeJSON(FLAGS_LS, { regions: REGIONS.join(','), titles: lockedTitles }); }

      // Pure, so the self-check can hit it: locked when every allowed country is one of ours.
      function limitedTo(allowed, regions) {
        if (!allowed || !allowed.length) return false;
        return allowed.every(function (r) { return regions.indexOf(r) !== -1; });
      }

      // videos.list, 50 ids and 1 quota unit per call. Resolves { id: { status: 'ok'|'gone', allowed } }; ids YouTube omits are deleted/private.
      function restrictions(ids) {
        var key = apiKey();
        if (!key) return Promise.reject(new Error('no API key'));
        var found = {};
        var batches = [];
        for (var i = 0; i < ids.length; i += 50) batches.push(ids.slice(i, i + 50));
        return batches.reduce(function (chain, batch) {
          return chain.then(function () {
            return fetch(YT + '?part=contentDetails&maxResults=50&key=' + encodeURIComponent(key) + '&id=' + batch.join(','))
              .then(function (res) {
                if (!res.ok) return res.text().then(function (t) { throw new Error('youtube ' + res.status + ': ' + t); });
                return res.json();
              })
              .then(function (j) {
                (j.items || []).forEach(function (item) {
                  var rr = item.contentDetails && item.contentDetails.regionRestriction;
                  // Only the allowed whitelist; a blocked list naming all-but-two countries would slip past.
                  found[item.id] = (rr && rr.allowed) || null;
                });
              });
          });
        }, Promise.resolve()).then(function () {
          var map = {};
          ids.forEach(function (id) { map[id] = (id in found) ? { status: 'ok', allowed: found[id] } : { status: 'gone', allowed: null }; });
          return map;
        });
      }

      function checkPlaylist(playlist) {
        return apiGet('/playlists/' + encodeURIComponent(playlist.id) + '/tracks').then(function (tracks) {
          var yt = tracks.filter(function (t) { return t.source === 'youtube' && t.sourceId; });
          if (!yt.length) return { playlist: playlist.name, total: 0, locked: [], gone: [] };
          return restrictions(yt.map(function (t) { return t.sourceId; })).then(function (map) {
            var locked = [], gone = [];
            yt.forEach(function (t) {
              var r = map[t.sourceId];
              // playlistId/trackId ride along for removal later; report() trims them for the console table.
              var row = { playlistId: playlist.id, playlistName: playlist.name, trackId: t.id, title: t.title, track: t.title + (t.artist ? ' - ' + t.artist : ''), url: 'https://youtu.be/' + t.sourceId };
              if (r.status === 'gone') gone.push(row);
              else if (r.status === 'ok' && limitedTo(r.allowed, REGIONS)) {
                locked.push(Object.assign(row, { allowed: r.allowed.join(',') }));
                lockedTitles[norm(t.title)] = r.allowed.length;
              }
            });
            return { playlist: playlist.name, total: yt.length, locked: locked, gone: gone };
          });
        });
      }

      // One playlist at a time: sequential YouTube calls, ordered log. A full scan resets flags first so a now-available track drops its pill, then persists.
      function checkAll(only) {
        if (!apiKey()) { log('no API key, cancelled'); return Promise.resolve([]); }
        return apiGet('/playlists').then(function (playlists) {
          var wanted = only ? playlists.filter(function (p) { return p.id === only || p.name.toLowerCase() === String(only).toLowerCase(); }) : playlists;
          if (!wanted.length) { log('no playlist matched "' + only + '"'); return []; }
          if (!only) lockedTitles = {};
          return wanted.reduce(function (chain, p) {
            return chain.then(function (acc) {
              return checkPlaylist(p).then(function (r) { log(r.playlist + ': ' + r.locked.length + ' locked, ' + r.gone.length + ' gone, of ' + r.total + ' youtube tracks'); return acc.concat([r]); });
            });
          }, Promise.resolve([])).then(function (results) { saveFlags(); return results; });
        });
      }

      function report(results) {
        var locked = [], gone = [];
        results.forEach(function (r) { locked = locked.concat(r.locked); gone = gone.concat(r.gone); });
        var lockedCols = function (r) { return { playlist: r.playlistName, track: r.track, allowed: r.allowed }; };
        var goneCols = function (r) { return { playlist: r.playlistName, track: r.track, url: r.url }; };
        if (locked.length) { log('playable only in ' + REGIONS.join('/') + ':'); console.table(locked.map(lockedCols)); }
        if (gone.length) { log('deleted or private:'); console.table(gone.map(goneCols)); }
        if (!locked.length && !gone.length) log('nothing region-locked or missing');
        return locked.length;
      }

      // Flatten results into removable offenders, gone first then region-locked.
      function offendersOf(results) {
        var out = [];
        results.forEach(function (r) {
          r.gone.forEach(function (g) { out.push(Object.assign({ why: 'deleted or private on YouTube' }, g)); });
          r.locked.forEach(function (l) { out.push(Object.assign({ why: 'only playable in ' + REGIONS.join('/') }, l)); });
        });
        return out;
      }

      function removeOffender(o) {
        return apiDelete('/playlists/' + encodeURIComponent(o.playlistId) + '/tracks/' + encodeURIComponent(o.trackId)).then(function () {
          delete lockedTitles[norm(o.title)];
          markRemoved(o.title);
          log('removed "' + o.track + '" from ' + o.playlistName);
          return true;
        }).catch(function (e) {
          log('remove failed for "' + o.track + '": ' + e.message);
          toast('Remove failed', o.track);
          return false;
        });
      }

      // ----------------------------------- ui ----------------------------------
      // Tabler's world icon, matching the toolbar's own icons.
      var WORLD = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="tabler-icon tabler-icon-world"><path d="M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path><path d="M3.6 9h16.8"></path><path d="M3.6 15h16.8"></path><path d="M11.5 3a17 17 0 0 0 0 18"></path><path d="M12.5 3a17 17 0 0 1 0 18"></path></svg>';

      // No id on the toolbar, so anchor on the Create button. Step out by parent, not closest('.inline-flex'): the button carries that class itself.
      function toolbar() {
        var create = document.querySelector('button[aria-label="Create playlist"]');
        var wrap = create && create.parentElement;
        var bar = wrap && wrap.parentElement;
        return bar && bar.classList.contains('flex') ? { bar: bar, before: wrap } : null;
      }

      function runCheck(btn) {
        if (btn.disabled) return;
        btn.disabled = true;
        var label = btn.getAttribute('aria-label');
        btn.setAttribute('aria-label', 'Checking regions...');
        btn.style.opacity = '.5';
        checkAll(null).then(function (results) {
          var n = report(results);
          btn.setAttribute('aria-label', n ? n + ' track(s) playable only in ' + REGIONS.join('/') + ' - see console' : 'No region-locked tracks');
          markRows();
          if (!toastUnavailable(results)) toast('Every track is available', 'nothing region-locked or missing');
          // Locked but no pill placed means the row markup moved; say so rather than look clean.
          if (n && !document.querySelector('.wz-region-flag')) log('found ' + n + ' locked track(s) but could not tag any row - run WZRegion.debug()');
        }).catch(function (e) {
          log('failed: ' + e.message);
          btn.setAttribute('aria-label', 'Region check failed - see console');
        }).then(function () {
          btn.disabled = false;
          btn.style.opacity = '';
          setTimeout(function () { btn.setAttribute('aria-label', label); }, 8000);
        });
      }

      function addButton() {
        if (document.getElementById('wz-region-btn')) return;
        var spot = toolbar();
        if (!spot) return;
        var wrap = document.createElement('div');
        wrap.className = 'inline-flex';
        var btn = document.createElement('button');
        btn.id = 'wz-region-btn';
        btn.type = 'button';
        btn.className = 'theme-button-neutral inline-flex h-9 w-9 items-center justify-center rounded-md';
        btn.setAttribute('aria-label', 'Region check');
        btn.title = 'Flag tracks YouTube only allows in ' + REGIONS.join('/');
        btn.innerHTML = WORLD;
        btn.addEventListener('click', function () { runCheck(btn); });
        wrap.appendChild(btn);
        spot.bar.insertBefore(wrap, spot.before);
      }

      function pill(count, key) {
        var el = document.createElement('span');
        el.className = 'wz-region-flag inline-flex shrink-0 items-center gap-1 rounded-md border border-rose-300/24 bg-rose-400/12 px-2 py-0.5 text-[10px] font-semibold tracking-[0.12em] text-rose-100 uppercase';
        el.dataset.wzTitle = key; // lets removal find this track's pill(s)
        var msg = 'YouTube only allows this track in ' + count + ' countr' + (count === 1 ? 'y' : 'ies') + ', all inside ' + REGIONS.join('/') + '.';
        el.title = msg;
        el.setAttribute('aria-label', msg);
        el.innerHTML = WORLD.replace('width="16" height="16"', 'width="11" height="11"') + REGIONS.join('/') + ' only';
        return el;
      }

      // After a DELETE, dim the row and swap its pill(s); wavez won't re-render until a reload.
      function markRemoved(title) {
        var key = norm(title);
        var pills = document.querySelectorAll('.wz-region-flag');
        for (var i = 0; i < pills.length; i++) {
          if (norm(pills[i].dataset.wzTitle) !== key) continue;
          var p = pills[i];
          p.className = 'wz-region-flag inline-flex shrink-0 items-center gap-1 rounded-md border border-emerald-300/24 bg-emerald-400/12 px-2 py-0.5 text-[10px] font-semibold tracking-[0.12em] text-emerald-100 uppercase';
          p.innerHTML = 'removed - reload';
          if (p.parentElement) { p.parentElement.style.opacity = '.5'; p.parentElement.style.textDecoration = 'line-through'; }
        }
      }

      // Normalise for matching: DOM titles carry NBSPs/doubled spaces the API title doesn't.
      function norm(s) {
        return (s || '').replace(/\s+/g, ' ').trim().toLowerCase();
      }

      function tag(el, n, key) {
        var host = el.parentElement;
        if (!host || host.querySelector('.wz-region-flag')) return false; // no parent, or already tagged
        host.appendChild(pill(n, key));
        return true;
      }

      // Match rows by title text across most elements; a full scan per re-render but only a few thousand nodes.
      function markRows() {
        var titles = Object.keys(lockedTitles);
        if (!titles.length) return;
        var nodes = document.querySelectorAll('span, p, div, a, h1, h2, h3, h4');
        var seen = {};
        var i, el, text;
        for (i = 0; i < nodes.length; i++) {
          el = nodes[i];
          if (el.children.length > 1) continue; // a wrapper, not the title line (one child allowed for a search highlight)
          text = norm(el.textContent);
          if (lockedTitles[text] === undefined) continue;
          if (el.children.length === 1 && norm(el.children[0].textContent) === text) continue; // tag the inner title node instead
          seen[text] = true;
          tag(el, lockedTitles[text], text);
        }
        // Fallback: title run into a duration/badge in the same leaf. Short extra text only, so it can't latch onto a row wrapper.
        var missing = titles.filter(function (t) { return !seen[t]; });
        if (!missing.length) return;
        for (i = 0; i < nodes.length; i++) {
          el = nodes[i];
          if (el.children.length) continue;
          text = norm(el.textContent);
          for (var j = 0; j < missing.length; j++) {
            if (text.length > missing[j].length && text.length < missing[j].length + 40 && text.indexOf(missing[j]) === 0) tag(el, lockedTitles[missing[j]], missing[j]);
          }
        }
      }

      // Render into the site's own toast stack if found (inherits its animation/placement), else a themed stack of our own. TOAST_HOST pins the selector if the guess is wrong.
      var TOAST_HOST = '';
      function toastHost() {
        var host = document.querySelector(TOAST_HOST || '[data-sonner-toaster], [data-radix-toast-viewport], .toaster, #toast-root');
        if (host) return { el: host, native: true };
        var own = document.getElementById('wz-region-toasts');
        if (!own) {
          own = document.createElement('div');
          own.id = 'wz-region-toasts';
          own.style.cssText = 'position:fixed;right:16px;bottom:16px;z-index:99999;display:flex;flex-direction:column;gap:8px;max-width:360px';
          document.body.appendChild(own);
        }
        return { el: own, native: false };
      }

      // action = { label, fn }: renders a button whose fn resolves truthy to dismiss. Action toasts linger and don't dismiss on a stray click, so the button is easy to hit.
      function toast(title, detail, action) {
        var host = toastHost();
        var el = document.createElement('div');
        el.className = 'wz-region-toast flex items-start gap-2 rounded-md border px-3 py-2 text-sm';
        if (!host.native) el.style.cssText = 'display:flex;gap:8px;align-items:flex-start;padding:10px 12px;border-radius:8px;border:1px solid var(--theme-field-border,rgba(255,255,255,.12));background:var(--theme-dropdown-bg,rgba(20,20,26,.96));color:var(--theme-text-primary,#e7e7ea);box-shadow:0 8px 20px rgba(0,0,0,.16);font:500 13px/1.35 system-ui,sans-serif';
        el.innerHTML = WORLD.replace('width="16" height="16"', 'width="14" height="14"') +
          '<span style="flex:1"><strong style="font-weight:600">' + esc(title) + '</strong>' + (detail ? '<br><span style="opacity:.7">' + esc(detail) + '</span>' : '') + '</span>';
        if (action) {
          var btn = document.createElement('button');
          btn.type = 'button';
          btn.className = 'theme-button-neutral shrink-0 rounded-md px-2 py-1 text-xs font-semibold';
          btn.style.cssText = 'border:1px solid var(--theme-field-border,rgba(255,255,255,.18));background:var(--theme-dropdown-hover,rgba(255,255,255,.06));color:inherit;cursor:pointer';
          btn.textContent = action.label;
          btn.addEventListener('click', function (e) {
            e.stopPropagation();
            btn.disabled = true;
            btn.textContent = '...';
            Promise.resolve(action.fn()).then(function (ok) { if (ok !== false) el.remove(); else { btn.disabled = false; btn.textContent = action.label; } });
          });
          el.appendChild(btn);
        } else {
          el.addEventListener('click', function () { el.remove(); });
        }
        host.el.appendChild(el);
        setTimeout(function () { el.remove(); }, action ? 20000 : 8000);
      }

      function esc(s) {
        var d = document.createElement('div');
        d.textContent = s;
        return d.innerHTML;
      }

      // One Remove toast per unavailable track, capped at 5 with a "Remove all" for the rest.
      function toastUnavailable(results) {
        var offenders = offendersOf(results);
        lastOffenders = offenders;
        offenders.slice(0, 5).forEach(function (o) {
          toast(o.track, o.why + ' - in ' + o.playlistName, { label: 'Remove', fn: function () { return removeOffender(o); } });
        });
        if (offenders.length > 5) {
          var rest = offenders.slice(5);
          toast(rest.length + ' more unavailable', 'full list in the console', { label: 'Remove all', fn: function () { return removeMany(rest); } });
        }
        return offenders.length;
      }

      // Sequential, to stay within rate limits; resolves to how many went.
      function removeMany(list) {
        return list.reduce(function (chain, o) {
          return chain.then(function (done) { return removeOffender(o).then(function (ok) { return done + (ok ? 1 : 0); }); });
        }, Promise.resolve(0)).then(function (done) { toast('Removed ' + done + ' of ' + list.length, 'reload to refresh the list'); return done; });
      }

      // Restore the last check's flags so pills come back on refresh. Ignored if REGIONS changed, since the pass/fail no longer holds.
      (function restoreFlags() {
        var f = readJSON(FLAGS_LS);
        if (f && f.regions === REGIONS.join(',') && f.titles) lockedTitles = f.titles;
      })();

      // React tears down and rebuilds the toolbar and rows, so a debounced observer re-adds the button and pills.
      var pending = null;
      new MutationObserver(function () {
        clearTimeout(pending);
        pending = setTimeout(function () { addButton(); markRows(); }, 200);
      }).observe(document.body, { childList: true, subtree: true });
      addButton();
      markRows();

      window.WZRegion = {
        // Check everything, or one playlist by name or id.
        check: function (only) { return checkAll(only).then(function (r) { var n = report(r); markRows(); toastUnavailable(r); return n; }); },
        // What the anchors currently resolve to, for when the markup shifts.
        debug: function () { console.log('toolbar:', toolbar()); console.log('toast host:', toastHost()); console.log('locked titles:', lockedTitles); },
        toast: function (a, b) { toast(a || 'Test toast', b || 'from wavez-region-check'); },
        // Log every leaf element containing the string, with its parent markup. For when a pill won't land.
        find: function (text) {
          var want = norm(text);
          var hits = [];
          var all = document.body.querySelectorAll('*');
          for (var i = 0; i < all.length; i++) {
            if (norm(all[i].textContent).indexOf(want) === -1) continue;
            if (all[i].querySelector('#wz-region-toasts, #wz-region-btn')) continue; // skip our own furniture
            if (!all[i].children.length) hits.push(all[i]);
          }
          hits.forEach(function (el) { console.log(el, '\nparent markup:\n' + (el.parentElement ? el.parentElement.outerHTML.slice(0, 700) : '(none)')); });
          if (!hits.length) log('nothing on screen contains "' + text + '"');
          return hits;
        },
        playlists: function () { return apiGet('/playlists').then(function (p) { console.table(p.map(function (x) { return { id: x.id, name: x.name, active: !!x.isActive }; })); return p; }); },
        setKey: function (k) { localStorage.setItem(KEY_LS, k); return 'saved'; },
        // Forget the persisted pills; they return on the next check.
        clearFlags: function () { localStorage.removeItem(FLAGS_LS); lockedTitles = {}; return 'cleared'; },
        // The last check's offenders, to eyeball what remove() would touch.
        unavailable: function () { console.table(lastOffenders.map(function (o) { return { playlist: o.playlistName, track: o.track, why: o.why }; })); return lastOffenders; },
        // Delete the last check's offenders. Narrow with 'gone', 'locked', or a title substring. Confirms first.
        remove: function (filter) {
          if (!lastOffenders.length) { log('run a check first (nothing to remove)'); return Promise.resolve(0); }
          var want = lastOffenders.filter(function (o) {
            if (!filter) return true;
            if (filter === 'gone') return o.why.indexOf('deleted') === 0;
            if (filter === 'locked') return o.why.indexOf('only playable') === 0;
            return norm(o.track).indexOf(norm(filter)) !== -1;
          });
          if (!want.length) { log('no offenders match ' + JSON.stringify(filter)); return Promise.resolve(0); }
          if (!window.confirm('Remove ' + want.length + ' track(s) from your playlists? This cannot be undone.')) return Promise.resolve(0);
          return removeMany(want);
        },
        regions: REGIONS
      };
      log('loaded - hit the globe in the playlist toolbar or run WZRegion.check()');

      if (location.hash === '#wz-region-test') {
        console.assert(limitedTo(['US', 'CA'], REGIONS) === true, 'US+CA only, flag it');
        console.assert(limitedTo(['US'], REGIONS) === true, 'US only, flag it');
        console.assert(limitedTo(['US', 'CA', 'GB'], REGIONS) === false, 'GB can play it, leave it');
        console.assert(limitedTo(['JP'], REGIONS) === false, 'JP only is not a US/CA lock');
        console.assert(limitedTo(null, REGIONS) === false, 'no restriction at all');
        console.assert(limitedTo([], REGIONS) === false, 'empty allowed list is not a lock');
        log('self-check passed');
      }
    })();
  })(PAGE);

})();
