// ==UserScript==
// @name         Wavez Tools (all-in-one)
// @namespace    https://wavez.fm/
// @author       fluteds
// @icon         https://wavez.fm/favicon.ico
// @version      2026.07.18
// @updateURL    https://github.com/fluteds/wavez/raw/main/userscripts/wavez-all.user.js
// @downloadURL  https://github.com/fluteds/wavez/raw/main/userscripts/wavez-all.user.js
// @description  Every Wavez userscript in one install. Toggle features from the userscript manager menu.
// @match        https://wavez.fm/*
// @match        https://*.wavez.fm/*
// @grant        GM_registerMenuCommand
// @grant        GM_registerMenuCommand
// @grant        GM_xmlhttpRequest
// @grant        unsafeWindow
// @connect      niceatc.api.br
// @connect      translate.googleapis.com
// @connect      woot.niceatc.api.br
// @run-at       document-idle
// ==/UserScript==

// GENERATED by sync-scripts.sh. Edit the individual scripts, not this file.

(function () {
  'use strict';

  // Taking a @grant sandboxes us, and the page-context scripts below reach for
  // page globals (window.WavezFM). Hand them the real window so they still work.
  var PAGE = typeof unsafeWindow !== "undefined" ? unsafeWindow : window;

  var KEY = "wavez-tools:";
  function on(id, dflt) { return (localStorage.getItem(KEY + id) || dflt) === "on"; }

  // The manager already has a menu. Native beats a settings panel we maintain.
  function menu(id, label, dflt) {
    var isOn = on(id, dflt);
    if (typeof GM_registerMenuCommand !== "function") return isOn;
    GM_registerMenuCommand((isOn ? "✓ " : "✕ ") + label, function () {
      localStorage.setItem(KEY + id, isOn ? "off" : "on");
      location.reload();
    });
    return isOn;
  }

  if (menu('translate', 'Wavez Translate', 'on')) (function (window) {

    // CONFIG Language to translate INTO (ISO code: "en", "es", "pt", "ja", ...).
    var TARGET_LANG = "en";

    // How translated text is shown. Change live from the console with WZTranslate.setMode(...). "append" = keep the original and add a dimmed translated line beneath it; "replace" = swap the message text for the translation (original kept on hover); "hover" = chat stays original and crossfades to the translation on hover (back on leave).
    var DISPLAY_MODE = "append";

    // Only translate messages NOT already in TARGET_LANG (uses Google's detected source language). Set false to translate everything.
    var ONLY_NON_TARGET = true;

    // Max simultaneous translation requests (keeps the free endpoint from rate-limiting).
    var MAX_INFLIGHT = 4;

    // --------------------------------------------------------------------------
    (function () {
      "use strict";

      // Chat message bodies carry a wavez-specific token, a stable hook across theme changes. System callouts (e.g. "Agente X moveu...") have no such token on text itself, so we anchor off the only wavez class in the callout the icon, and grab the paragraph beside it.
      var MSG_SELECTOR =
        '[class*="wavezfm-chat-text-size"], .wavezfm-centered-icon + div > p';

      var config = {
        target: TARGET_LANG,
        mode: DISPLAY_MODE,
        onlyNonTarget: ONLY_NON_TARGET,
        enabled: true,
      };

      // --- styling -------------------------------------------------------------
      var style = document.createElement("style");
      style.textContent =
        ".wz-translation{display:block;margin-top:2px;opacity:.6;font-style:italic;" +
        "font-size:var(--wavezfm-chat-text-size,13px);line-height:var(--wavezfm-chat-line-height,1.25rem)}" +
        ".wz-translation::before{content:'\\1F310\\00A0';opacity:.7}" +
        ".wz-replaced::before{content:'\\1F310\\00A0';opacity:.5;font-size:.85em}" +
        ".wz-hover{cursor:pointer;transition:opacity .15s ease,transform .15s ease}" +
        ".wz-hover.wz-swap{opacity:0;transform:translateY(3px)}";
      (document.head || document.documentElement).appendChild(style);

      // --- cross-origin GET (GM first, fetch fallback) -------------------------
      function httpGet(url) {
        return new Promise(function (resolve, reject) {
          if (typeof GM_xmlhttpRequest === "function") {
            GM_xmlhttpRequest({
              method: "GET",
              url: url,
              onload: function (r) {
                resolve(r.responseText);
              },
              onerror: reject,
              ontimeout: reject,
            });
            return;
          }
          if (typeof GM !== "undefined" && GM.xmlHttpRequest) {
            GM.xmlHttpRequest({
              method: "GET",
              url: url,
              onload: function (r) {
                resolve(r.responseText);
              },
              onerror: reject,
              ontimeout: reject,
            });
            return;
          }
          // No GM API (e.g. raw injection): the endpoint sends CORS *, so plain fetch works in most setups.
          fetch(url)
            .then(function (r) {
              return r.text();
            })
            .then(resolve, reject);
        });
      }

      // --- concurrency-limited queue -------------------------------------------
      var inflight = 0;
      var queue = [];
      function pump() {
        while (inflight < MAX_INFLIGHT && queue.length) {
          var job = queue.shift();
          inflight++;
          job().then(release, release);
        }
      }
      function release() {
        inflight--;
        pump();
      }
      function enqueue(fn) {
        return new Promise(function (resolve, reject) {
          queue.push(function () {
            return fn().then(resolve, reject);
          });
          pump();
        });
      }

      // translation cache: original text -> { text, src }
      var cache = Object.create(null);

      function translate(text) {
        if (cache[text]) return Promise.resolve(cache[text]);
        return enqueue(function () {
          var url =
            "https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=" +
            encodeURIComponent(config.target) +
            "&dt=t&q=" +
            encodeURIComponent(text);
          return httpGet(url).then(function (raw) {
            var data = JSON.parse(raw);
            var out = (data[0] || [])
              .map(function (seg) {
                return seg && seg[0] ? seg[0] : "";
              })
              .join("");
            var result = { text: out, src: data[2] || "" };
            cache[text] = result;
            return result;
          });
        });
      }

      // --- rendering -----------------------------------------------------------
      function clearTranslation(el) {
        if (el._wzNode && el._wzNode.parentNode) {
          el._wzNode.parentNode.removeChild(el._wzNode);
        }
        el._wzNode = null;
        if (el._wzOriginal != null) {
          el.textContent = el._wzOriginal;
          el._wzOriginal = null;
        }
        if (el._wzHover) {
          // Restore the original markup if we're mid-swap, then drop hover state.
          if (el._wzHover.shown) el.innerHTML = el._wzHover.html;
          el._wzHover = null;
        }
        el.classList.remove("wz-hover", "wz-swap", "wz-replaced");
        el.removeAttribute("title");
      }

      // Crossfade between the original markup and the translation on hover. We keep a busy flag so the MutationObserver ignores our own text swaps.
      function swapHover(el, toTranslated) {
        var h = el._wzHover;
        if (!h || h.shown === toTranslated) return;
        h.shown = toTranslated;
        el._wzBusy = true;
        el.classList.add("wz-swap"); // fade + nudge out
        window.setTimeout(function () {
          if (!el._wzHover) {
            el.classList.remove("wz-swap");
            el._wzBusy = false;
            return;
          }
          if (toTranslated) el.textContent = h.translated;
          else el.innerHTML = h.html;
          el.classList.remove("wz-swap"); // fade back in
          // Clear busy after the mutation records have been delivered.
          window.setTimeout(function () {
            el._wzBusy = false;
          }, 0);
        }, 150);
      }

      function setupHover(el, translated) {
        el._wzHover = { html: el.innerHTML, translated: translated, shown: false };
        el.classList.add("wz-hover");
        if (!el._wzHoverBound) {
          el._wzHoverBound = true;
          el.addEventListener("mouseenter", function () {
            swapHover(el, true);
          });
          el.addEventListener("mouseleave", function () {
            swapHover(el, false);
          });
        }
      }

      function render(el, original, translated) {
        clearTranslation(el);
        if (config.mode === "replace") {
          el._wzOriginal = original;
          el.textContent = translated; // drops inline emoji <img>; use hover mode to keep them
          el.classList.add("wz-replaced"); // leading 🌐 marks the swap
          el.title = original;
          return;
        }
        if (config.mode === "hover") {
          setupHover(el, translated);
          return;
        }
        // append (default)
        var node = document.createElement("span");
        node.className = "wz-translation";
        node.textContent = translated;
        el._wzNode = node;
        el.parentNode.insertBefore(node, el.nextSibling);
      }

      // At least two letters worth translating (skip pure emoji/numbers/links).
      var LETTERS = /\p{L}{2,}/u;

      function process(el) {
        if (!config.enabled || el._wzBusy) return;
        var original = (el.textContent || "").trim();
        if (!original || !LETTERS.test(original)) return;
        // Skip if this is text we've already handled - either the source we translated, or the translation itself currently swapped in on hover.
        if (original === el._wzSrc || original === el._wzTranslated) return;
        el._wzSrc = original;

        translate(original)
          .then(function (res) {
            // Element text changed while we were translating, bail, the observer will re-fire for the new content.
            if ((el.textContent || "").trim() !== original) return;
            el._wzTranslated = res.text.trim();
            var sameLang =
              res.src &&
              res.src.toLowerCase().split("-")[0] === config.target.toLowerCase();
            var unchanged =
              res.text.trim().toLowerCase() === original.toLowerCase();
            if (config.onlyNonTarget && (sameLang || unchanged)) {
              clearTranslation(el);
              return;
            }
            if (unchanged) {
              clearTranslation(el);
              return;
            }
            render(el, original, res.text);
          })
          .catch(function () {
            // Network/parse error: allow a retry next time the node is seen.
            if (el._wzSrc === original) el._wzSrc = null;
          });
      }

      function scan(root) {
        if (!root || root.nodeType !== 1) return;
        if (root.matches && root.matches(MSG_SELECTOR)) process(root);
        var nodes = root.querySelectorAll
          ? root.querySelectorAll(MSG_SELECTOR)
          : [];
        for (var i = 0; i < nodes.length; i++) process(nodes[i]);
      }

      // --- observe chat --------------------------------------------------------
      var observer = new MutationObserver(function (mutations) {
        for (var i = 0; i < mutations.length; i++) {
          var m = mutations[i];
          for (var j = 0; j < m.addedNodes.length; j++) scan(m.addedNodes[j]);
          // Text swapped in place (React re-render): re-check the target element.
          if (m.type === "characterData" && m.target.parentNode) {
            var p = m.target.parentNode;
            if (p.matches && p.matches(MSG_SELECTOR)) process(p);
          }
        }
      });
      observer.observe(document.body, {
        childList: true,
        subtree: true,
        characterData: true,
      });

      // Catch messages already on screen at load.
      scan(document.body);

      // --- live controls -------------------------------------------------------
      function retranslateAll() {
        var nodes = document.querySelectorAll(MSG_SELECTOR);
        for (var i = 0; i < nodes.length; i++) {
          nodes[i]._wzSrc = null;
          process(nodes[i]);
        }
      }

      // Expose controls on the page window (unsafeWindow) so they're reachable from the DevTools console; under a sandboxed @grant the script's own `window` isn't the page's.
      var pageWindow = typeof unsafeWindow !== "undefined" ? unsafeWindow : window;
      pageWindow.WZTranslate = {
        config: config,
        setMode: function (mode) {
          config.mode = mode;
          // Re-render every message in the new layout.
          var nodes = document.querySelectorAll(MSG_SELECTOR);
          for (var i = 0; i < nodes.length; i++) {
            nodes[i]._wzSrc = null;
            clearTranslation(nodes[i]);
            process(nodes[i]);
          }
        },
        setTarget: function (lang) {
          config.target = lang;
          cache = Object.create(null);
          retranslateAll();
        },
        enable: function () {
          config.enabled = true;
          retranslateAll();
        },
        disable: function () {
          config.enabled = false;
          var nodes = document.querySelectorAll(MSG_SELECTOR);
          for (var i = 0; i < nodes.length; i++) clearTranslation(nodes[i]);
        },
        retranslateAll: retranslateAll,
      };

      console.log(
        "%c[wz-translate] active → " +
          config.target +
          " (mode: " +
          config.mode +
          "). Controls: WZTranslate.setMode('append'|'replace'|'hover')",
        "color:#30C7FB;font-weight:bold",
      );
    })();
  })(PAGE);

  if (menu('spotify', 'Wavez Open in Spotify', 'on')) (function (window) {

    (function () {
      'use strict';

      const ID = 'wavez-open-spotify-btn';

      // Drop YouTube-style descriptor tags in ()/[] ("Official Video", "Lyrics", "HD"...). No track:/artist: filters: the source artist is a YouTube channel handle ("enyatv"), so plain text search on the "Artist - Title" string beats it.
      const stripNoise = (s) => (s || '')
        .replace(/[([][^)\]]*\b(officials?|video|audio|lyrics?|visuali[sz]er|m\/?v|hd|4k|remaster(?:ed)?|explicit)\b[^)\]]*[)\]]/gi, '')
        .replace(/\s{2,}/g, ' ')
        .trim();

      function spotifyUrl(titleEl) {
        const pb = window.WavezFM?.version === '1'
          ? window.WavezFM.room.getState()?.playback
          : null;
        const query = stripNoise(pb?.title || titleEl.textContent);
        return 'https://open.spotify.com/search/' + encodeURIComponent(query);
      }

      function addButton() {
        const title = document.querySelector('#wavezfm-current-track-title-desktop');
        const yt = document.querySelector('a[aria-label="Open on YouTube"]');

        if (!title || !yt || document.getElementById(ID)) return;

        const row = title.closest('.flex');
        if (!row) return;

        const wrap = document.createElement('div');
        wrap.className = 'inline-flex shrink-0';
        wrap.id = ID;

        const link = yt.cloneNode(false);
        link.href = '#';
        link.setAttribute('aria-label', 'Open on Spotify');
        link.title = 'Open on Spotify';
        link.style.color = '#ffffff';
        link.style.display = 'inline-flex';
        link.style.visibility = 'visible';
        link.style.opacity = '1';

        link.innerHTML = `
        <svg xmlns="http://www.w3.org/2000/svg"
             width="12"
             height="12"
             viewBox="0 0 24 24"
             fill="currentColor">
          <path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10 10-4.5 10-10S17.55 2 12 2zm3.75 14.65c-2.35-1.45-5.3-1.75-8.8-.95-.35.1-.65-.15-.75-.45-.1-.35.15-.65.45-.75 3.8-.85 7.1-.5 9.7 1.1.35.15.4.55.25.85-.2.3-.55.4-.85.2zm1-2.7c-2.7-1.65-6.8-2.15-9.95-1.15-.4.1-.85-.1-.95-.5-.1-.4.1-.85.5-.95 3.65-1.1 8.15-.55 11.25 1.35.3.15.45.65.2 1s-.7.5-1.05.25zM6.3 9.75c-.5.15-1-.15-1.15-.6-.15-.5.15-1 .6-1.15 3.55-1.05 9.4-.85 13.1 1.35.45.25.6.85.35 1.3-.25.35-.85.5-1.3.25C14.7 9 9.35 8.8 6.3 9.75z"/>
        </svg>
        `;

        link.onclick = (e) => {
          e.preventDefault();
          e.stopPropagation();

          window.open(spotifyUrl(title), '_blank');
        };

        wrap.appendChild(link);

        const titleBox = title.parentElement;
        row.insertBefore(wrap, titleBox);
      }

      setInterval(addButton, 500);

      if (location.hash === '#wz-spotify-test') {
        const cases = [
          ['Groove Is In The Heart (Official Video)', 'Groove Is In The Heart'],
          ['Song [Official Audio]', 'Song'],
          ['Track (Official Music Video) [HD]', 'Track'],
          ['Title (Lyrics)', 'Title'],
          ['Da Funk (Remastered)', 'Da Funk'],
          ['Power (feat. Dwele)', 'Power (feat. Dwele)'], // real parens kept
        ];
        cases.forEach(([raw, want]) =>
          console.assert(stripNoise(raw) === want, 'stripNoise:', raw, '->', stripNoise(raw), 'want', want));
        console.log('[wz-spotify] self-check passed');
      }
    })();
  })(PAGE);

  if (menu('chat-toggle', 'Wavez Chat Toggle', 'on')) (function (window) {

    (function () {
      'use strict';

      const KEY = 'wavez-chat-hidden';

      const css = document.createElement('style');
      css.textContent = `
        #wavez-chat-rail-toggle {
          position: fixed;
          top: 50%;
          transform: translateY(-50%);

          width: 20px;
          height: 58px;

          padding: 0;
          border: 1px solid var(--theme-border);
          border-right: 0;
          border-radius: 8px 0 0 8px;

          background: var(--theme-room-nav);
          color: color-mix(in srgb, var(--theme-text-primary) 56%, transparent);

          box-shadow: -8px 0 18px rgba(0,0,0,.22);

          z-index: 2147483647;
          cursor: pointer;

          display: flex;
          align-items: center;
          justify-content: center;

          opacity: .82;
          transition:
            opacity .2s ease,
            color .2s ease,
            background .2s ease;
        }

        #wavez-chat-rail-toggle:hover {
          opacity: 1;
          color: white;
          background: var(--theme-button-neutral-hover);
        }

        #wavez-chat-rail-toggle svg {
          width: 11px;
          height: 11px;
          flex-shrink: 0;
          transition: transform .2s ease;
        }

        #wavez-chat-rail-toggle:hover svg {
          transform: scale(1.12);
        }

        #wavez-chat-rail-toggle.chat-hidden svg {
          transform: rotate(180deg);
        }

        #wavez-chat-rail-toggle.chat-hidden:hover svg {
          transform: rotate(180deg) scale(1.12);
        }

        #wavez-chat-rail-toggle.has-new::after {
          content: '';
          position: absolute;
          top: 6px;
          right: 6px;
          width: 7px;
          height: 7px;
          border-radius: 50%;
          background: var(--theme-accent, #f43f5e);
          box-shadow: 0 0 0 2px var(--theme-room-nav);
        }
      `;
      document.head.appendChild(css);

      function getRail() {
        return document.querySelector('[data-room-desktop-rail="true"]');
      }

      function makeButton() {
        const btn = document.createElement('button');
        btn.id = 'wavez-chat-rail-toggle';
        btn.type = 'button';
        btn.setAttribute('aria-label', 'Toggle chat');

        btn.innerHTML = `
          <svg xmlns="http://www.w3.org/2000/svg"
               viewBox="0 0 24 24"
               fill="none"
               stroke="currentColor"
               stroke-width="2.4"
               stroke-linecap="round"
               stroke-linejoin="round">
            <path d="M9 6l6 6l-6 6"></path>
          </svg>
        `;

        document.body.appendChild(btn);
        return btn;
      }

      function init() {
        const rail = getRail();
        if (!rail || document.getElementById('wavez-chat-rail-toggle')) {
          return false;
        }

        const btn = makeButton();

        function apply() {
          const hidden = localStorage.getItem(KEY) === 'true';

          rail.style.display = hidden ? 'none' : '';
          btn.classList.toggle('chat-hidden', hidden);

          // Opening the chat clears the unread dot.
          if (!hidden) btn.classList.remove('has-new');

          if (hidden) {
            btn.style.right = '0px';
          } else {
            const rect = rail.getBoundingClientRect();

            // Makes the handle stick out slightly from the chat rail
            btn.style.right = `${window.innerWidth - rect.left - 1}px`;
          }
        }

        btn.addEventListener('click', () => {
          const hidden = localStorage.getItem(KEY) === 'true';
          localStorage.setItem(KEY, String(!hidden));
          apply();
        });

        window.addEventListener('resize', apply);

        // Flag an unread dot when a message arrives while chat is hidden.
        const markUnread = () => {
          if (localStorage.getItem(KEY) === 'true') btn.classList.add('has-new');
        };

        const api = window.WavezFM;
        if (api && api.version === '1') {
          // Bridge fires only on real chat messages - no false positives from unrelated rail DOM churn.
          api.room.subscribe('chat_message', markUnread);
        } else {
          new MutationObserver((records) => {
            if (records.some((r) => r.addedNodes.length)) markUnread();
          }).observe(rail, { childList: true, subtree: true });
        }

        apply();
        return true;
      }

      const wait = setInterval(() => {
        if (init()) {
          clearInterval(wait);
        }
      }, 500);
    })();
  })(PAGE);

  if (menu('imgur', 'Wavez Imgur -> Rimgo Safe', 'on')) (function (window) {

    (function () {
      'use strict';

      const ALTSITE = 'https://rimgo.vern.cc';

      function rewrite(value) {
        if (!value || !value.includes('imgur.com')) return value;

        return value.replace(
          /https?:\/\/(?:i\.|m\.|www\.)?imgur\.com/gi,
          ALTSITE
        );
      }

      function fixElement(el) {
        if (!el || el.nodeType !== 1) return;

        for (const attr of ['href', 'src', 'srcset', 'data-src', 'poster', 'style']) {
          const oldValue = el.getAttribute(attr);
          if (!oldValue || !oldValue.includes('imgur.com')) continue;

          const newValue = rewrite(oldValue);
          if (newValue !== oldValue) {
            el.setAttribute(attr, newValue);
          }
        }
      }

      // niceatc/nicewoot renders its badge from a CSS rule injected as a <style> block (e.g. --nw-badge-img: url("https://i.imgur.com/...png")), not from an element attribute - so the stylesheet text needs rewriting too.
      function fixStyleEl(el) {
        if (!el || el.tagName !== 'STYLE') return;

        const css = el.textContent;
        if (!css || !css.includes('imgur.com')) return;

        const next = rewrite(css);
        if (next !== css) el.textContent = next;
      }

      // Rules built with insertRule() (no <style> text node) only live in the CSSOM, so rewrite them in place. Recurse into @media/@layer/@supports groups.
      function fixRules(parent) {
        let rules;
        try {
          rules = parent.cssRules;
        } catch (e) {
          return; // cross-origin sheet, not readable
        }
        if (!rules) return;

        for (let i = 0; i < rules.length; i++) {
          const rule = rules[i];

          // Grouping rule (@media, @layer, @supports) - descend.
          if (rule.cssRules && rule.cssRules.length) {
            fixRules(rule);
            continue;
          }

          const text = rule.cssText;
          if (!text || !text.includes('imgur.com')) continue;

          const next = rewrite(text);
          if (next === text) continue;

          try {
            parent.deleteRule(i);
            parent.insertRule(next, i);
          } catch (e) {
            // malformed rule - skip
          }
        }
      }

      function fixSheets(root) {
        let sheets = [];
        // document.styleSheets / ShadowRoot.styleSheets cover <style> + <link>.
        try {
          if (root.styleSheets) sheets = sheets.concat(Array.from(root.styleSheets));
        } catch (e) {}
        // Constructed sheets attached via adoptedStyleSheets.
        try {
          if (root.adoptedStyleSheets) sheets = sheets.concat(Array.from(root.adoptedStyleSheets));
        } catch (e) {}
        sheets.forEach(fixRules);
      }

      function scanStyles(root) {
        root = root || document;
        // Styles usually live in <head>, so scan the whole document, not just body.
        root.querySelectorAll?.('style').forEach(fixStyleEl);
        fixSheets(root);
      }

      // Cross-origin CSS (e.g. niceatc/nicewoot badge sheet). The badge image lives in a remote stylesheet the browser won't let us read via the CSSOM (sheet.cssRules throws cross-origin). So refetch it ourselves, rewrite imgur -> rimgo in the raw CSS, inject the result as a local <style>, and disable the original <link> so the imgur-referencing version stops applying. Needs @grant GM_xmlhttpRequest + @connect for the host.
      const REMOTE_CSS_HOST = 'niceatc';
      const remoteCss = new Map(); // href -> 'pending' | 'done' | 'clean' | 'failed'

      function gmFetch() {
        if (typeof GM_xmlhttpRequest !== 'undefined') return GM_xmlhttpRequest;
        if (typeof GM !== 'undefined' && GM.xmlHttpRequest) return GM.xmlHttpRequest;
        return null;
      }

      function importRemoteCss(link) {
        const href = link.href;
        if (!href) return;

        let url;
        try { url = new URL(href, location.href); } catch (e) { return; }
        if (url.origin === location.origin) return;          // same-origin = readable elsewhere
        if (!url.hostname.includes(REMOTE_CSS_HOST)) return; // only the niceatc sheet

        const state = remoteCss.get(href);
        if (state === 'done') { link.disabled = true; return; } // keep replacements disabled
        if (state) return;                                      // pending / clean / failed

        const fetcher = gmFetch();
        if (!fetcher) return; // no cross-origin read available (script needs @grant)

        remoteCss.set(href, 'pending');
        fetcher({
          method: 'GET',
          url: href,
          onload(res) {
            const css = res.responseText || '';
            if (!css.includes('imgur.com')) { remoteCss.set(href, 'clean'); return; }
            const style = document.createElement('style');
            style.setAttribute('data-rimgo-import', href);
            style.textContent = rewrite(css);
            (document.head || document.documentElement).appendChild(style);
            link.disabled = true;
            remoteCss.set(href, 'done');
          },
          onerror() { remoteCss.set(href, 'failed'); }
        });
      }

      function scanRemoteCss() {
        document.querySelectorAll('link[rel~="stylesheet"]').forEach(importRemoteCss);
      }

      function scan(root) {
        if (!root) return;

        if (root.nodeType === 1) {
          fixElement(root);
          fixStyleEl(root);
        }

        root.querySelectorAll?.('[href*="imgur.com"], [src*="imgur.com"], [srcset*="imgur.com"], [data-src*="imgur.com"], [poster*="imgur.com"], [style*="imgur.com"]')
          .forEach(fixElement);

        root.querySelectorAll?.('style').forEach(fixStyleEl);

        // Descend into shadow roots (userscript widgets often isolate their UI).
        root.querySelectorAll?.('*').forEach(el => {
          if (el.shadowRoot) {
            scan(el.shadowRoot);
            scanStyles(el.shadowRoot);
          }
        });
      }

      function start() {
        scan(document.body);
        scanStyles();
        scanRemoteCss();

        const observer = new MutationObserver(mutations => {
          for (const mutation of mutations) {
            if (mutation.type === 'childList') {
              mutation.addedNodes.forEach(scan);
            }

            if (mutation.type === 'attributes') {
              fixElement(mutation.target);
            }
          }
        });

        // Observe <html> so injected <head> <style> blocks are caught too.
        observer.observe(document.documentElement, {
          childList: true,
          subtree: true,
          attributes: true,
          attributeFilter: ['href', 'src', 'srcset', 'data-src', 'poster', 'style']
        });

        // Fallback for scripts that inject/rewrite styles or backgrounds after load.
        setInterval(() => {
          scan(document.body);
          scanStyles();
          scanRemoteCss();
        }, 1500);
      }

      if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', start);
      } else {
        start();
      }
    })();
  })(PAGE);

  if (menu('auto-woot', 'Wavez Auto Woot', 'off')) (function (window) {

    // Uses the official extension API: https://github.com/WavezFM/WavezFM-Extension-API
    (function () {
      'use strict';

      var enabled = localStorage.getItem('wavez-autowoot') !== 'off';
      var lastKey = null;

      // Vote only on a new track we haven't already wooted, and only when allowed. playbackKey is the API's track-change signal; clientVote is our own vote.
      function shouldVote(key, last, votes) {
        return !!key && key !== last && !!votes && votes.canVote && votes.clientVote !== 'woot';
      }

      function voteCurrent(api) {
        if (!enabled) return;
        var state = api.room.getState();
        var pb = state && state.playback;
        if (!pb) return;
        // Only stamp lastKey on an actual vote. Stamping on the skip marked a track as handled when votes just weren't ready yet (canVote still false), and nothing ever retried it - the main reason woots got missed in a background tab, where the state lands later relative to playback_changed.
        if (!shouldVote(pb.playbackKey, lastKey, state.votes)) return;
        lastKey = pb.playbackKey;
        var res = api.actions.vote('woot');
        if (!res || !res.ok) console.warn('[wz-woot] vote failed:', res && res.code);
      }

      function init(api) {
        voteCurrent(api); // catch the track already playing at load
        api.room.subscribe('playback_changed', function () { voteCurrent(api); });
        // Retry once the vote state actually arrives for the new track.
        api.room.subscribe('votes_changed', function () { voteCurrent(api); });
        // Backstop for a hidden tab: events can be missed or arrive throttled, and a re-check is free (shouldVote gates it, so no redundant API calls). Timers are throttled in the background, but wavez is playing audio, which exempts the tab from Chrome's harshest throttling - worst case this lands late.
        setInterval(function () { voteCurrent(api); }, 30000);

        window.WZWoot = {
          now: function () { lastKey = null; voteCurrent(api); }, // force a woot
          on: function () { enabled = true; localStorage.setItem('wavez-autowoot', 'on'); voteCurrent(api); },
          off: function () { enabled = false; localStorage.setItem('wavez-autowoot', 'off'); },
          get enabled() { return enabled; }
        };
        console.log('[wz-woot] auto-woot ' + (enabled ? 'on' : 'off') + ' - toggle with WZWoot.on() / WZWoot.off()');
      }

      // The bridge may be injected after document-idle, so wait for it.
      var tries = 0;
      var wait = setInterval(function () {
        var api = window.WavezFM;
        if (api && api.version === '1') {
          clearInterval(wait);
          init(api);
        } else if (++tries > 40) {
          clearInterval(wait); // ~20s, give up quietly (not in a room, or API gone)
        }
      }, 500);

      // Quick check on the vote guard: load with #wz-woot-test.
      if (location.hash === '#wz-woot-test') {
        var ok = { canVote: true, clientVote: null };
        console.assert(shouldVote('k1', null, ok) === true, 'new track, can vote');
        console.assert(shouldVote('k1', 'k1', ok) === false, 'same track, skip');
        console.assert(shouldVote('k2', 'k1', { canVote: false, clientVote: null }) === false, 'cannot vote, skip');
        console.assert(shouldVote('k2', 'k1', { canVote: true, clientVote: 'woot' }) === false, 'already wooted, skip');
        console.assert(shouldVote(null, 'k1', ok) === false, 'no playbackKey, skip');
        console.log('[wz-woot] tests passed');
      }
    })();
  })(PAGE);

  if (menu('auto-grab', 'Wavez Auto Grab', 'off')) (function (window) {

    // Track changes and "have I already grabbed this?" come from the official extension API (https://github.com/WavezFM/WavezFM-Extension-API), but grab itself is NOT in it - actions are vote/joinQueue/leaveQueue/sendChat/setVolume only - so the grab itself clicks the real button and picks from the picker.
    (function () {
      'use strict';

      // Playlist to grab into, by name. "" = whichever the picker lists first.
      var PLAYLIST = 'Recs';

      // Only set these if the heuristics below match the wrong element. Run WZGrab.debug() in the console to see what they currently find.
      var GRAB_BTN_SELECTOR = '';
      var PICKER_SELECTOR = '';

      var LS_KEY = 'wavez-autograb';
      // Default off: unlike a woot, a grab writes to your playlist.
      var enabled = localStorage.getItem(LS_KEY) === 'on';
      var lastKey = null;

      function log(m) { console.log('[wz-grab] ' + m); }

      // Grab a track once you've wooted it, and only once. playbackKey identifies the track; clientVote is your own vote; clientGrabbed is "already in a playlist". Works with a manual woot or an auto-woot script - both land as clientVote.
      function shouldGrab(key, last, votes) {
        return !!key && key !== last && !!votes &&
          votes.clientVote === 'woot' && !votes.clientGrabbed;
      }

      // ---------------------------------- dom ----------------------------------
      function visible(el) {
        return el.offsetParent !== null;
      }

      // The vote buttons carry no aria-label or id, just utility classes. Two things are stable though: the count span is themed with --theme-vote-grab, and the label sits in its own span ("Grab") next to the count. Prefer the theme var, it survives a relabel (the site has pt-BR locales); fall back to the label.
      function findGrabButton() {
        if (GRAB_BTN_SELECTOR) return document.querySelector(GRAB_BTN_SELECTOR);
        var btns = document.querySelectorAll('button');
        var byLabel = null;
        for (var i = 0; i < btns.length; i++) {
          if (btns[i].querySelector('[style*="theme-vote-grab"]')) return btns[i];
          if (byLabel) continue;
          // Match the label span exactly: the button's own textContent reads "Grab0".
          var spans = btns[i].querySelectorAll('span');
          for (var j = 0; j < spans.length; j++) {
            if (spans[j].textContent.trim().toLowerCase() === 'grab') { byLabel = btns[i]; break; }
          }
        }
        return byLabel;
      }

      // The popup carries no role/dialog attributes, only data-wavezfm-grab-menu-root which the wrapper around the Grab button carries too. The popup is the one that does NOT contain the button. It's only in the DOM while the menu is open.
      function findPicker() {
        if (PICKER_SELECTOR) return document.querySelector(PICKER_SELECTOR);
        var btn = findGrabButton();
        var roots = document.querySelectorAll('[data-wavezfm-grab-menu-root]');
        for (var i = 0; i < roots.length; i++) {
          if (btn && roots[i].contains(btn)) continue; // that's the wrapper
          if (visible(roots[i])) return roots[i];
        }
        return null;
      }

      // An option's textContent runs the name into the subtitle ("RecsPlaylist - 53/300"), so read the name span instead. Same span the header's "Choose a playlist" uses, but that's a <p>, and Cancel is filtered out before we get here.
      function nameOf(el) {
        var span = el.querySelector('span.truncate');
        return (span ? span.textContent : el.textContent).trim();
      }

      // The second truncate span, e.g. "Active - 58/300" or "Playlist - 53/300".
      function detailOf(el) {
        var spans = el.querySelectorAll('span.truncate');
        return spans.length > 1 ? spans[1].textContent.trim() : '';
      }

      // Every playlist button in the open picker. Full playlists come back too, but disabled - callers decide whether to care.
      function optionsIn(picker) {
        var items = picker.querySelectorAll('button');
        var out = [];
        for (var i = 0; i < items.length; i++) {
          if (items[i].getAttribute('aria-label') === 'Cancel') continue; // header close
          if (visible(items[i])) out.push(items[i]);
        }
        return out;
      }

      function closePicker(picker) {
        var cancel = picker.querySelector('[aria-label="Cancel"]');
        if (cancel) cancel.click();
      }

      // Open the picker (if it isn't), hand the options to cb, and say whether we were the one who opened it so the caller can close it again.
      function withPicker(cb) {
        var open = findPicker();
        if (open) return cb(optionsIn(open), null);
        var btn = findGrabButton();
        if (!btn) { log('grab button not found - are you in a room?'); return cb([], null); }
        btn.click();
        waitFor(findPicker, 2000, function (picker) {
          if (!picker) { log('picker did not open'); return cb([], null); }
          cb(optionsIn(picker), picker);
        });
      }

      // Poll for fn() to go truthy, up to ms. The picker opens asynchronously.
      function waitFor(fn, ms, cb) {
        var waited = 0;
        var t = setInterval(function () {
          var v = fn();
          if (v) { clearInterval(t); cb(v); }
          else if ((waited += 100) >= ms) { clearInterval(t); cb(null); }
        }, 100);
      }

      function choosePlaylist(picker) {
        // Full playlists (300/300) come through disabled, so they can't be grabbed into.
        var options = optionsIn(picker).filter(function (el) { return !el.disabled; });
        if (!options.length) { log('picker opened but listed no playlists'); return; }

        var pick = options[0];
        if (PLAYLIST) {
          pick = options.filter(function (el) {
            return nameOf(el).toLowerCase() === PLAYLIST.toLowerCase();
          })[0];
          if (!pick) {
            log('playlist "' + PLAYLIST + '" not in the picker (full or renamed?), skipping');
            return;
          }
        }
        pick.click();
        log('grabbed into "' + nameOf(pick) + '"');
      }

      function doGrab() {
        var btn = findGrabButton();
        if (!btn) { log('grab button not found - set GRAB_BTN_SELECTOR'); return; }
        btn.click();
        waitFor(findPicker, 2000, function (picker) {
          if (!picker) { log('no picker appeared, assuming the grab went straight through'); return; }
          choosePlaylist(picker);
        });
      }

      function grabCurrent(api) {
        if (!enabled) return;
        var state = api.room.getState();
        var pb = state && state.playback;
        if (!pb) return;
        // Only stamp lastKey on an actual grab: a track sits un-wooted for a while before you woot it, and stamping on the skip would dedupe that away.
        if (!shouldGrab(pb.playbackKey, lastKey, state.votes)) return;
        lastKey = pb.playbackKey;
        doGrab();
      }

      // ----------------------------------- ui ----------------------------------
      function buildUI(api) {
        var css = document.createElement('style');
        css.textContent =
          '#wz-grab-pill{position:fixed;right:14px;bottom:14px;z-index:99999;' +
          'display:flex;gap:6px;align-items:center;padding:7px 12px;border-radius:999px;' +
          'background:rgba(20,20,26,.86);border:1px solid rgba(255,255,255,.12);' +
          'font:500 12px/1 system-ui,sans-serif;color:#e7e7ea;cursor:pointer;user-select:none;opacity:.6}' +
          '#wz-grab-pill.on{opacity:1}' +
          '#wz-grab-pill input{accent-color:#ff5c8a;margin:0;cursor:pointer}';
        document.head.appendChild(css);

        var pill = document.createElement('label');
        pill.id = 'wz-grab-pill';
        pill.title = 'Grab a track into "' + (PLAYLIST || 'the first playlist') + '" whenever you woot it';
        if (enabled) pill.className = 'on';

        var box = document.createElement('input');
        box.type = 'checkbox';
        box.checked = enabled;
        box.addEventListener('change', function () {
          enabled = box.checked;
          localStorage.setItem(LS_KEY, enabled ? 'on' : 'off');
          pill.className = enabled ? 'on' : '';
          if (enabled) grabCurrent(api);
        });

        pill.appendChild(box);
        pill.appendChild(document.createTextNode('auto grab'));
        document.body.appendChild(pill);
      }

      // ---------------------------------- init ---------------------------------
      function init(api) {
        grabCurrent(api); // catch a track that's already wooted at load
        // The woot is the trigger, so watch votes, not playback.
        api.room.subscribe('votes_changed', function () { grabCurrent(api); });
        buildUI(api);

        window.WZGrab = {
          on: function () { enabled = true; localStorage.setItem(LS_KEY, 'on'); grabCurrent(api); },
          off: function () { enabled = false; localStorage.setItem(LS_KEY, 'off'); },
          now: function () { lastKey = null; doGrab(); }, // force a grab
          get enabled() { return enabled; },
          // Your playlist names, for copying into PLAYLIST. Opens the picker, reads it, closes it again - opening it doesn't grab, only clicking an option does. Async: the table prints once the menu has rendered.
          playlists: function () {
            withPicker(function (options, opened) {
              if (options.length) {
                console.table(options.map(function (el) {
                  return {
                    playlist: nameOf(el),
                    detail: detailOf(el),
                    full: !!el.disabled,
                    target: nameOf(el).toLowerCase() === PLAYLIST.toLowerCase()
                  };
                }));
              }
              if (opened) closePicker(opened);
            });
          },
          // What the heuristics currently match, for pinning the selectors.
          debug: function () {
            console.log('grab button:', findGrabButton());
            console.log('picker (open it first):', findPicker());
          }
        };
        log('auto grab ' + (enabled ? 'on' : 'off') + ' - toggle with the corner pill or WZGrab.on()/off()');
      }

      // The bridge may be injected after document-idle, so wait for it. Say so up front: without this line a missing bridge and a missing script look identical in the console, since WZGrab is only defined once init() runs.
      log('loaded, waiting for the WavezFM bridge...');
      var tries = 0;
      var wait = setInterval(function () {
        var api = window.WavezFM;
        if (api && api.version === '1') {
          clearInterval(wait);
          init(api);
        } else if (++tries > 40) { // ~20s
          clearInterval(wait);
          console.warn('[wz-grab] WavezFM bridge never appeared, so WZGrab is unavailable. ' +
            'Are you inside a room? window.WavezFM is currently ' + typeof window.WavezFM + '.');
        }
      }, 500);

      if (location.hash === '#wz-grab-test') {
        var wooted = { clientVote: 'woot', clientGrabbed: false };
        console.assert(shouldGrab('k1', null, wooted) === true, 'wooted, not grabbed');
        console.assert(shouldGrab('k1', 'k1', wooted) === false, 'already grabbed this track, skip');
        console.assert(shouldGrab('k2', 'k1', { clientVote: null, clientGrabbed: false }) === false, 'not wooted yet, skip');
        console.assert(shouldGrab('k2', 'k1', { clientVote: 'meh', clientGrabbed: false }) === false, 'mehed, skip');
        console.assert(shouldGrab('k2', 'k1', { clientVote: 'woot', clientGrabbed: true }) === false, 'already in a playlist, skip');
        console.assert(shouldGrab(null, 'k1', wooted) === false, 'no playbackKey, skip');
        console.log('[wz-grab] tests passed');
      }
    })();
  })(PAGE);

})();
