#!/usr/bin/env sh
# Refresh the published userscripts in ./userscripts from the source repo,
# stamping each one with update/download URLs that point back at this repo.
set -e
cd "$(dirname "$0")"
src=../userscripts/wavez
raw=https://github.com/fluteds/wavez/raw/main/userscripts
author=fluteds

bundle=userscripts/wavez-all.user.js

n=0
for dest in userscripts/*.user.js; do
  name=$(basename "$dest")
  [ "$dest" = "$bundle" ] && continue
  if [ -f "$src/$name" ]; then
    cp "$src/$name" "$dest"
    n=$((n + 1))
  else
    echo "  keep (no source): $name"
  fi

  # stamp author, and point update/download URLs at this repo
  awk -v url="$raw/$name" -v author="$author" '
    /^\/\/ @(author|updateURL|downloadURL)/ { next }
    { print }
    /^\/\/ @namespace/ { printf "// @author       %s\n", author }
    /^\/\/ @version/ {
      printf "// @updateURL    %s\n", url
      printf "// @downloadURL  %s\n", url
    }
  ' "$dest" > "$dest.tmp" && mv "$dest.tmp" "$dest"
done
echo "synced $n script(s) from $src"

# ---- all-in-one bundle -------------------------------------------------
# Concatenates the scripts above, each behind a toggle. Feature order is fixed
# so the output is stable. Automation is off by default; the rest ship on.
features="wavez-translate:translate:on
wavez-open-in-spotify:spotify:on
wavez-sidebar:chat-toggle:on
wavez-imgur:imgur:on
wavez-auto-woot:auto-woot:off
wavez-auto-grab:auto-grab:off
wavez-region-check:region-check:off"

# Union of every feature's @grant/@connect: the bundle needs them all. Read the
# standalone sources only - globbing the bundle back in re-feeds its own @grant
# lines, duplicating GM_registerMenuCommand on every rebuild.
sources=$(ls userscripts/*.user.js | grep -vF "$bundle")
grants=$(grep -h '^// @grant' $sources | grep -v 'grant *none' | awk '{print $3}' | sort -u)
connects=$(grep -h '^// @connect' $sources | awk '{print $3}' | sort -u)

{
  echo '// ==UserScript=='
  echo '// @name         Wavez Tools (all-in-one)'
  echo '// @namespace    https://wavez.fm/'
  echo "// @author       $author"
  echo '// @icon         https://wavez.fm/favicon.ico'
  echo "// @version      $(date +%Y.%m.%d)"
  echo "// @updateURL    $raw/$(basename "$bundle")"
  echo "// @downloadURL  $raw/$(basename "$bundle")"
  echo '// @description  Every Wavez userscript in one install. Toggle features from the userscript manager menu.'
  echo '// @match        https://wavez.fm/*'
  echo '// @match        https://*.wavez.fm/*'
  echo '// @grant        GM_registerMenuCommand'
  echo "$grants" | sed 's|^|// @grant        |'
  echo "$connects" | sed 's|^|// @connect      |'
  echo '// @run-at       document-start'
  echo '// ==/UserScript=='
  echo
  echo '// GENERATED by sync-scripts.sh. Edit the individual scripts, not this file.'
  echo
  echo "(function () {"
  echo "  'use strict';"
  echo
  echo '  // Taking a @grant sandboxes us, and the page-context scripts below reach for'
  echo '  // page globals (window.WavezFM). Hand them the real window so they still work.'
  echo '  var PAGE = typeof unsafeWindow !== "undefined" ? unsafeWindow : window;'
  echo
  echo '  var KEY = "wavez-tools:";'
  echo '  function on(id, dflt) { return (localStorage.getItem(KEY + id) || dflt) === "on"; }'
  echo
  echo '  // The manager already has a menu. Native beats a settings panel we maintain.'
  echo '  function menu(id, label, dflt) {'
  echo '    var isOn = on(id, dflt);'
  echo '    if (typeof GM_registerMenuCommand !== "function") return isOn;'
  echo '    GM_registerMenuCommand((isOn ? "✓ " : "✕ ") + label, function () {'
  echo '      localStorage.setItem(KEY + id, isOn ? "off" : "on");'
  echo '      location.reload();'
  echo '    });'
  echo '    return isOn;'
  echo '  }'
  echo

  echo "$features" | while IFS=: read -r file id dflt; do
    label=$(grep -m1 '^// @name' "userscripts/$file.user.js" | sed 's|^// @name *||')
    echo "  if (menu('$id', '$label', '$dflt')) (function (window) {"
    # strip the metadata block, keep the body, indent it into the wrapper
    awk '/==\/UserScript==/ { body = 1; next } body' "userscripts/$file.user.js" |
      sed 's|^\(.\)|    \1|'
    echo "  })(PAGE);"
    echo
  done

  echo "})();"
} > "$bundle"

echo "built $(basename "$bundle") ($(echo "$features" | wc -l | tr -d ' ') features, $(wc -l < "$bundle" | tr -d ' ') lines)"
